import PySimpleGUI as sg
import locale
from datetime import datetime
import sqlite3
import gettext
import re
import logging
import grafico as gr
from dateutil.relativedelta import relativedelta
_ = gettext.gettext

# en = gettext.translation('en', localedir='locale', languages=['en'])
# en.install()
# _ = en.gettext # English

logo64 = b'iVBORw0KGgoAAAANSUhEUgAAAEEAAABECAYAAADeOlj2AAAACXBIWXMAAAsSAAALEgHS3X78AAAQlElEQVR4nM1cC3Qc1Xn+7szsW6uVVlrJkvXyAxv8iGRDcMoJtYtxDA7UcShNGrc8Cglxepxi6IOCncPBrk+B1olDKPGhQOHkpOEQHOy6peDW2ITSmjgOwjHYMrb1sCTrtXrue2em55/d2Z2dGe3OrmROv3PWnpl7587c7/73f907YrIs47PAv7xYywDMAbAYwCYAHgAbANRN8/jXALwtyzglivLpP/nW4NSVes0rSkK64wsA3Alg9zTVTgNYmq8dSUJEkuSzsoxtAN6764HB5Gy+5xUh4SfP19h5nt0P4BEAjVbuqazgTgJY6a/kjpuVj0/Iq6JRKTQ6JnGSjN2yLP/9vVuGorPxvrNKwiv7agQA9wB4nuMQ5XlGjbvM6pZ7OdTW8KfLvZyT5xVpsYxkUu4cGpaksQnx4NCw+PC9W4akmbz3rJHwyr6aNQDe0V/neTbOcbABcDvsDI0Nwjl/JUe6wTsbzxVFDI+Miq9+fCa+9b4/GyqpMzMm4YVnAy6bwA4CuHm6OhU+Dgvn2y46HGzejB6WB5KEy4zh0YVt3S8Ve++MSHjh2cAKACcZAziODXAMtdpyh4Nh2RL7RWeeznMcRh0ONuV0sDKHnVVyHGC3s0x5MikjmQQSSTkSi8nBSFQWRDH3OTq005Rc0Nr9odV+lEzCC88GSPE9n9MYA3iODTCG2nkttp76ObypUhR4DHu9HO9xs0pBYGZV8oKICY5KY1Mh2cZxiqnVYxzAgwtau//ZSntFk/DjHwQYz+PnHIevmpWXeTi0Lrd32wTWpC9zu9hAhY+r1Y70TCBJwC//Jyo2NQgRxlBm0tTLC1q775lVEogAAK+S3VdGnccwY6hWy+vnCMFFC21kIcq19zmdbLjaz1WXMupW8ItDIZpC8tKr7VETa1SQCMskaAnQXuc4RHge8YXzbVMN9cJcXdl4TTXvczqvTOe1ICJ6ekVsWOcKCQLTT5G8RHBWHyJJ+LmegPR11/Il9lE9AW43CzbUCwUJuNAp49RpWfl/Jth0mweVPg4H/i3sGQlKcV1Td59vb3p8uuYtScIzT1ffn3aAIjzP6AE+tWxlq72zys+3aOtX+bmIt4wzdZL0+PZDDgwMhBFPSFi7msPmP+RQGyhNckhh7ntpEhOTEr50kzte5efsuiqbFrR2v6G/ryAJzzxdrZhB7TXVG1zZah/QEsAYIrUB3lWM+D+6M6U+Lg+EMTwShSjK2LiBw+Y7eXjM9H4BDAyKePEnk0ql225xR71lnFNzB1mNlgWt3WM5/cnX5N4nq316ApCaAs6mBiGuJ6CutjgCtJhT68Y1iyvhK7fjxy9O4Qs3j5bUTm0Nj6sX2ZTjt/8r4hRFTGiKqT8Gs5mXBFGUX5Ikhb0cVPl5LL7KlpkSKgEzNX08z+B2CxgfjyMcLj1QvHWdW/k/npBx+J0wiVpEU7zxfHvTGm39aUnYs7uKKm4SRdlHc02SMEDXXS6G6691TGrrlkIAzcJLfUAsJhZ1nxU4HQzXrXAoNUfHJJw+E3fqbstRkqYk7NldJWiDIXphUZRriYzrr3V2MZYNfkgJFkMAtfXWEYav3wc89BjQ0xvCpb4QEgljIHiyvXTJuvGGbL8/+m2cyTK0SZnVWmkwJUGW8ZDZ9YXzbWMeN2tWz8kMWrUChLFx4O4tPF75GYMgcIr4k9MVjYro6plSyJClrKLe8bdxfOWPJQwMWn1CFiQNDfVC5vzIuxG9R/mgemCwDk8+UVXBGEZ5LtcbdLsY1t3knlC9QfL/6+uEas6ip9HTy/D43wmQJDklWZKsHCOlexQ9MBKMYmIibioVNQEXXnvZhYa5vGUiOj5N4PWDocz51+8om9K515VkKcy6sIVeMimiOikqUqHoghWtjk+07nB1FW+ZgKkQw+5/cCgjTxLAcYwCLQg8B0mU0dk5gY5zYxgZiZoSQBgcimD1hiBeP2A9mTS/Rcg5/+i3cb3R/Qr00+HJJxRdkMkFpsmo9fv5WHUVf416vayMGy7GFD79jDNFAM9BUIhgsNk4RKJJ/KZ9GEPD5h1bvtSv/LT4q+9N4vCRmKXn0nMog6Xi0wsJemntw4wkALjdrLFr2xxd6jGZQ38FV21WzwzDQQ4Tkxx4gUGwceAUIjjE4yLaPxrJjDyRcv11Nfi91fVZEpb5lZ/HkzuiO58KFXpsBosW2jLHZDKjMTmsKd5oRsKP9I1QVsjtYovU83IvF7c6DQj/9IpLEf/MNOAZeIFD+6kgksksATetrse8ltyMWyKhmGbUBnJ1b2+/iOMnEpaev1hDAuFsR6JSe05WItOdXTv8dcmkXC/LGNZWal1m/0Q9JinwlXM+WISsWAReGXmOpQigDvf1hzA5mY1xvnjDHFRUOAyNNjeKitIsLzeW/e+v9DGSObze3BHrupTUz+M2bY0vKzogKVeLokwe1rjNxhCozuqCYqUgGk09L5V7SOkEOu7oyLruc+s9iuY3w5Y/DeFbd4dRX28MIhrqrVkJcu60CIUU6dPqhRZtl76nHlB4nEjIvoZ6PsdCe8uYZSkwAxEwNZVAOJJ1iacjQMX8liR++GQYD36nInPtns0u3LFR7wRahyjmhAJtisbZtcPvMlskWb7EnlEiDgfrEQRmaSElH4Z06yUVFfpo1wgay60P2LD1gUDRzyOnSY/xCcnjr8yOv3p0tb6i3cYoZZWJEss8zLJFyId4YvZjhWIhijkeYkYn3KJvp6lRCGrPPW7r7rEKl7Nwwqa3z7q5u0LwqZKwQt/+vBahUz0mF7kYhajFHbdH8pZf6jUPnmYL0VjhgVC7Zsgd+rxZU+h2cyUPV9vncu253Zar1SlvcPjIpSsSUk+HRAI5zgO3a4dfMKtrs7HMIqnTmY0ciwUl4P9yazaKDQSMWn1yMoFDb3bjxMkhhEJZy5Gw5g/lBYX/xr4hp2WSBMOiRU0gd7TsNn2N4lDll/DYw5PwlUuo8DkQqDaqF/Iez1+YwAcnslZ5/Vej2POPImayXBoMFpxqx0xnOlkGLWZj0cRbJuORbVOK89PWWqV4joXQ1T2JZ/cFsXRVEI88bi1o0qO3v3CazvRNGhuEzEYJWjAt6ekmYGnn57k9MfzNwwFLRBBIX7z2iwnceMuI5ZhBxacXjCRUVnBan7uz4FvwHJsoVKdYEBl3/5GEt9+oREuz9W0Kff0SvnHfmOWcAgVfl/qMJPA8007wwiRcSTQ1cFj1+RrcdmszFl3lQ4WvsPcIJZSmVFxhazI+YdQHNNUZy1kr/dBUEsrK2AxVYXGgfMGK1mqsX9eYySfQVKH0uxkmp2TsfS5c8BlnOoyRZkWFocvmJPx/AFmRL9/SjDU31ptak/0HC0+Jo+8Z6yxbYtdq2K4Frd3KdDDsD5yakmfBQs8MdbUpcQ8EXFjzu/WmuiOfkhwcEsm/MQRQgSpe6/gdpX+47TuDeW2IJMulx6wzQELMffm2z1VbtiaE/zwWoZAZopTaNkRm3uOh7Ba0SUtlcVZt9bXpGiuwP6ggDr3FsO1Rhu/8BcPHZ637G2NjuXWJALNpYYZYTEZff1ZxkpWgXEbbcrtWm46rK9QqCW9r2+q5lFylPTdzPa3gQieHg2/aMDLKY3QMeOIp4Bvf5HCpt/DNSRP5tJJ7IPz3cXN90ThX0E6FzBK9SsJRbWXKyhZ6ISu42GVDWZkd5V4byjw22G2csuCy9a8l3Pa1JC50Tu/SptL9co7LHIvl6oBrFhutB1mOs58adcXiq2yyzjRmVqdVEjq1N5BS0SIckQdKIWFes6h03OMmMmzweu2IRkR8dGoEn5wZxbqNI8qiihkkWVZC7ERSUlariIvhkazJIwLKvcbp9ebhEOIxGbRx1KFRiouvsmkXkckqZAZeISGtHN/XNpZIyOfV43BYsr72pUFjQ0qEaD467DzKPALOnM31wjvOGVb+FcgSEI+JSMRFhYz+y2FlqU7FvZuN+oG8w/7LqQEkiaPVLSKjrlYgJ0krBdOuSj+mLRgcEjPMKUtyJegFCqPXr82aZUZs6AZvuswSSQKl4mgbTzicUKRHxdw63pBoTSSB1w8Y2yIybljl0LoBXfr9jVoS3tMWXOhMtmnPQ2G5pEBqzRdjWL4kO0fNNDwtz+tBukAl4PgHgznrFE/vMvoMR45FMqZQi2sW22XdIqxhA1eGhPSUeFQ9J9GSZWSkYXxCKinBRq+0+c6IEkJTPmHRQmPW/mLnBHr7w5kVKSjTUUJn1ySO/2oQU6EsiU894cWq63K9+o/PJnD+YiJjCl3OFBm0kr5ooU1rKtrNdrnq1etz2gXZkVHxXLWfX4mUrfVFozJK3ZNEITTlEz4+I6Cz26t0UMXoaAzt7amFL2XK0P6aSFL5qfCWMezb6zMQ0NWdxNFf5ipXWk2nZm68wRXRbe58ECbIGd3tO4O0NPRD9bz9VHyltjw4KpVkJVRQ95ZencThN5z40tqshNImjcmphPKbmMwNeqjz3/22G+/+R5WBANqq99aRCDxu48CsWO4QnU6mJWCv1iJoYSbiD6sHZCrDYblDPY8n5NpwWC4cvhUAZa6f2+PCsTf904bQpPxI9Knzf77FYzCHRMCr+0PKiMcTqeyXSkZzkyDX1fFai9ZupgtUmO5j3LXDn/mAg/KNa1dnCWUM0ca5grPUFLwe6j5GFeQ3vHOsTxn1n75QYXrPyIiI/YfMx4I2mP/O9Q7SA6r5IBu8Jt/Wf9OubN8ZPKrGE3ppkGU4B4fFYbP7Pgt0nE/gX98KQxCUPVM5T/SWGQhAest/3m8f8o3n18h60cG770cWaQuiUbl6fEKalY+wyKu0AtredPS9CN5PxwU0DWj/AjlDtHuOCPjC5w0E7LXyzcO0JGzfGZTT3zD20F7As+cSPdry0THJOTkl5V9esoBv3hXC/XeF85IxOirhwKEQ+i4b65BT5StnZgTQznZTa6BH3pm9fWcwohJxsj3WOBWSLmrLR4KSazaImN+cVMj4g99PNUUWgWIDCuRO/CaGfz8cpvhFcaUpSSJoVN78FpvctlzZxKEnoODHHios7XJPL92ftdtY4+23uju1q9Uocle7FZCYf/DrGDq7pw9faRosW2KPOp1Mn/QpigAU89FHernup5UV3J3r17ontbtakXKmQs2NgocvKdRKuclj4xLOdCTQ05vqPCm/SMT4fg1zBbm5USCHQr+PZ9uC1u4fFPvsor+B2rXDv6mygtu/fq1bvzFS+Zy3rz/pCAR4rrFeUHz56Uih1BeN+EhQQvelZKbjetDr0TIgTQdfOUexwATP535elDaD95h9y2AFJX0NR9PD5WLfv/Vm9waHw7h7JZ6QQxcuJj2hsKR0djqQD6LPXZihvo6X6+cIIY4z/djrWJqAzoINTYMZfRd58Gdzmmtr+f1qfGGCibFxydV/OWmjjI8ZKNghE6ddKCHpoU2YzU3CmN2mzHmzZC+N/uOliL8es/KZ8K/fbbjXV87tZAxz81SLyjJC4Yis+Mh9/UmvKiX1dXxUEFjcYUeSdrkB8Odph/By2gkaK1DPEmbtW+kzJxrpQ89tjOG72m+kZhHj6eTo4zMRfTPM+p8OON/eVJHeM0yOSussNHkg3fk3Zmvk9biif0TifHtTS5oQCsgoU2Vlxwspug/TvyvWcS0+sz8nouJ8exORYRYefvhZdNgAAP8Hy8JtYewsOr4AAAAASUVORK5CYII='
logo_grande64 = b'iVBORw0KGgoAAAANSUhEUgAAATcAAAFGCAYAAAAPXNhWAAAACXBIWXMAAAsSAAALEgHS3X78AAAgAElEQVR4nO29CZgcZbn3fVdV77OvSSZ7JgtJCJNAIBgUwiaogCAv53xubCqKqMB1DoIK56jh4IJygr64o8DxqHwIAoKibAEBQRAyBLIvM5N1JrNPT+9V9V53dVXS6fRSVc/zVFd3P7/rmivbdHdNp/vf93P/70VQVRU4HBr89pdTPABQq9/Vcv3XDgBYlXH3lwDATBsP9woAvJHx5z/ov44BwG78zUev7h/l/5EcAy5uHEv89pdTBABoAIC5ADAHAM7Rf/8BlzyTe3Th2wgAOwBgKwAc+ujV/SkXXBvHQbi4cfLy219OCQLAdACYr4tXoagLI6vVLn82fwAA63Xh6+GCV9lwceMc5re/nNKoHycvITg+PgsAZ5fJs4pR3o8B4ClZVrd/4jMDYRdcE4cSXNyqmCwx+xLlZ6KcRA7wbSDLKh5j71FVeAIAdl7+2QH+5ihjuLhVEXrCH/NklwHAtTYjM6uUw3H1MPh2SKXUMT2v+BAAfAuPsZd/doAfYcsMLm4Vjp43Q7fy87qolYIDADAMAEvL5dlWFIjKsprQRQ640JUfXNwqEF3QzgeAf3dZ1PQuADQDwDQXXIspZFkdUxTwAUAw4/tR6L7Kj67uhotbhaAfOZcBwFdKGKGZ5d1yiuIgLXKDigKtOf7pMwDw+8s/O8Br7FwGF7cy57e/nDJfF7M7yvAnKTvTQVHUfkWBKTn+GXOLV/Bozj1wcStD9CjtQgC42yFTgDXl6Kz2q2pOkcPykssB4CWemystXNzKiN/+cgrmqm5hULbhFsrOWcXjqqrmPK6CfmS9j4tcaeDi5nL0diesRfu/5fTGJ8CUsxoKCeCRBO33gYAwXFcrbM/+nvo6sVYQ4BhhmQirqqKo8cy/kxWoGx5Wlhh/Hp9QTP8EOZzV7H//jgrq16+69lCM8LnhWICLm0vRRe0MAHigQo6elmioF0ckCZSmRnGH3y94A35BEgShVpKg08nrUFU4IMvqQCyuyvG4mhwZVZalUhDKJX55nFXjfkBR1W+DCv951ecPJZy6/mqGi5vLeOCn7ZhPu1IQ4OeiKPSLYs68TsWAEVhtjTjcUC/21dUKgscjzAOAunL4+VD4Uil1eHxCCQ+PKKsiERXiCdUQuXxRXFQF9T8VBb73qesO8TcfQ7i4uQRD1ADg55lXJAgAkiT0C0L5i5zfJ0BDw1FC1uWCy6LNRCym7hybUEJDw3LbyIjSlOv+FQX2q6Deoijway5ybODiVmLyiVo2usgNCkLe5LXrwKisqVHa3dIkjgUCQme5RGS0SSTVTf39cnBoRJk7OXn0cVZR4B1VVa+56vOH/l4JP6ub4OJWIh74aTvm1M4DgD9buQJRhKgkCXmT16VEkgBamqXh1haxpyYkThOE8ulEcJCJibCyfd9++cShYVl7VD0ftwEALrjq2kP7quR5YA4XN4fRRY3YKJAkYUwUcyevncSIzqa0S4JH0pryORaIxtQN+w+kZg0OKc3JpIoi93tQ4QtXff5QP38eyeDi5iAP/LQduwnup1nSoYucF3XGqZ8EBa1jqmd7U6NWasGjM0pMhJU3MaIbHJKxE+JnAPBF7qzah4ubAzzw03bcK/BfrIpvMR/H2llFM2DKFGnPlDbJwwWNORODQ/LB3b2pmdGYsg4AvnbVtYfMF95xNLi4MUQ/gn6qmFlAC9qmg5FDmzHdM86PnKUhnlC37d2bqtl3MPUV7qxag4sbI/Qj6HOlKMAlLR+prxNhxnTpzdoa8UT6V8exg6LAwYP9cnxgMPWZSz/R/zR/EovDxY0yemnH993Q/2nFWTWitFkzPMlKLxwuZ1QVwuMTyu6hEfnfz73owF+r/fkoBBc3ijzw0/Y1APC8265LFCEmSYKay1nFXNrMGZ7tzU3i1GqtQytXJieVl6Jx9bpVZ+57u9qfi1xwcaPAAz9tD+ouqKuHRGY6q3j0nDPLsyEQEJabuCnHxcQT6h8FAW5cvHLPTv7/dAQuboS4NVrLR2ODCPPneXf7/cJcd14hxy7JlPqIAPDpRSftGeFPIhc329x7T1tQkoSHRAE+VA7XO3WKNDx7pmfc4xG461nZ4OYuLB9Z19nVV9Wjz7m42eDee9pWAMBj6IQeLr8Ad/Z8NjaIA4sX+dRqMQkEAaIeSRjI9W+KqgZkuWrMkl4A+HpnV999LriWksDFzQL33tMm6JNwj9lXoDmTont6PhvqRVgw37vN7xMWuuBybCOKMCKJwrjHC6LXI2AhayAUFDSBEkUAn08guv9USoWUPs4ymVKjySQMKIrqicchJStqvaJAzqkeZcQLAHBDZ1ffhjL/OSzDxc0k997ThtvZ3y5WtyaJpe35rKkRYfGi8hM1SYJ+j0dI+H2CEggIsz0SuXDRIpFQsc4MIlG1P55QE8mkWluGoveNajuqcnEzwb33tFk2DXSRcyyK8/sFWNDp3dxQLy526jHtgkLm8wmJgF+o9fuEpkDAHSJmBRQ7FD1D8BIJtVVVSzvEwAR4VL2ys6tvvcuvkwpc3AqgH0PX2S3IPdzzyXDQpMej1ant6ZgqoZDWs3ocElDMggEhFQqJ0wN+QTtOViIodtGYOhKJquF4XHXzaPi79XxcRUdxXNzygG4oADxDY4KHZjqI9KfptrZIgws6vbLbzALMk/n9QriuVpxZyWJWjEhUxUkfe+JxVx5jKz6K4+KWg3vvacO+0DdomwO0RA6PoMcv8e0OuKhWTYvOgqJUXyu0uiVX5iYwqhsPq4ORiCK5TOju7uzqu8EF10EdLm5Z3HtP28cA4H9ZPgaJszp3jhePoK448ngkGKyrE6WakNCEx2OOOTCiG59Q9kxOqtMkCTwueNq6AeDizq6+HhdcCzW4uOmQ5tfsoPV8irl7PrPB0o4lx/lKvg0Lj5yhkCg31gutXNDIQFPiwEE5fmhI9mPnSIkZ04+pj5btE5oFF7cj+bWS9YbqzmrOabooIJ1zPdtbW6QFpbg2g2BQ2IM5tFCQCxptsNbu8T9HoalRhLmzSx7IVcwxterFTRe2raVefJzLWS11tCaKMNZQLyp1tWJTtZoCTvL3f8Tg9bcSMG+2B5Ys9iVEQauXLAUv6MfUsnZTq1rcdONguwsu5TAocn6fODR/nme0tUVydLu6gc8r9Dc3iVPKsf6s3Onbk4L/fSiM/wewbKlPWdDpTQoC+EvwY/XqAle2nQ1VK25uFDaktkaE5ct8PaVocA8F06LGc2mlJTypwP2/CaPpcFjkFs73ogEVcPjCyjoPV5Xi9pN1bZ/2eOBbbltwPGuGZ3TeHG+jk4+Jjeb1dWKioV5s4EdP94B5uD8+FYEt25LaNaHIrVzhl2fP8iRLIHJXlWMDftWJGwqbsbAlPdEDqBfXWgUjpZOW+3cHA87VrXFRKw/+8MTkYYEDXeTOPjMYaawXHVvlqHN/Z1ffleX03FWNuP1kXVveTVQoch6PFoI7PtEDSwC6jveHBQFqnXg8LmrlR/fGBPzp6chR143O6lmnB8d9PsHJlruyEriqEDdd2B4sVuqRXqgCjo0tmj/Pu2dGh8cxl7ahXhzjolae5BI4ZMkin9q1zIevWadMh7JxUite3MwKWyaSBEzHFuExtOt43666WnEei/vPhhsFlcG2HUl4+PHJY34WPKq+d3UgPqVNckrgsKNhjdsFrqLFzY6wZSJJMCiKdE0HdENP7PI7UrvGSzoqj5FRBX7yy/GcP1d7m4RHVadSHK4XuIoVN1JhM0gX1wIVMeqY6hleON/rYT2aCItvmxpFX12t6Pb5YhwbFBI4h6M4VwtcRYobLWHLhNRZdSq/xvNq1UEhgUMWdHrVlSv8TuTiXCtwFSduLIQtE6vOKua5lh7n297UKDLtDcUjaGuLOIWPG6oe+gdk+OWvJ/L+vBjFfei8UCQQEFiXjbhS4CpK3FgLWyZmnFUUtlUn+fd4vQKziE0QINLYIIoN9aLThZ0cF5DPRc1k9SkBLP6VGF9td2dXn6sWfFfa4eUXTk32UBQIJpPQoChaFBfN/nc0Dk5bFQizFDafTxicPk0KcWGrXrqW+eCD5xYOzF75R0x69gXtJRpj+ER17eye5aouhoqJ3DI7D0qBXj6iRXFaYe4y/4QAUMfiUni0xskGJ4qsf6mwduFmtA+eG5z0eIQahk+gawp9K0LcSi1sBpiPmznDM7Bovred1WNgtNbeKvJBkZxjyG7VygXm4da8L5hoaRZZjlO6sbOrb12p/4fKXtx+sq7tEgB4xAWXAjM6PMOLF3mbWd1/U6MY49EapxD/87sw7N2vb5kugAN5uJI325e1uP1knXvGFi1b6ts+tZ3NtFysW5vaLjVwJ5RTDJwm8tNfTWjjkoqht26xelGN6Q5qyebBla24/fDO1vmCANs9HqEkDe+ZnNjl62lplpjMXwuFhOHWZqmZ161xzILz4H740/w1cJno9XBxRmOU8L05p1QlImUpbj+8s/Wo0eDpsgx726RIYSlsLc1itJK6DDa+q0I4osKuHhUmJ0H7tf8QwMAhFdrbBLjmShHeczJXcRoYE33NgBNGzj8nFGMkcCUrESk7cfvhna3YvrQr184DSRKYNrxnw0rYKu0Y+rFPCzA2njD1vcuWCPDxyyRYtpQfwUl5+vkovPFW3NS9MBa4kjioZfUx+cM7W/EV/5t8y1xkWW1IJtWgXnvGFFbChm7ojA5PxQjbyKgIc2bXaV8+b/GX28ZNKtzyjRSsvVOG/kN8MxsJ554ZhPo6c29xbOd66plIgFEt3BU7u2dxcSvCLWaKdFHkMLGqKNDP4iJYCVttrTjYMVVqraT82shY+odpqPfB4uOaYOaMWoywi97u1dcVuPq6FNx1j6wdYTn2+NTl5kstGQvcup3dsxw9npbNsfSHd7auAYDnrd4u3fAuUBslzkrYKi2/ZrCr1wO/eODoCnpZVuHQYBQGh2La74tREwL48IdEuPiDEtSwLD+tUKzk34DtEdXRHtSyiBHQGbUjbAhqdyqlTsFITlVhkOQ6WAgbjv3umCpBNY0nwsht6pQQLF7UBM1NxYdWTEYAfvOQAlddl4THnixe4sA5mlkzPbhcxvSzwjCC68IIzqn/HteLm+6MPkd6P7rItcqyGtUtakuwEDaPB4anT5OC1Vq/hiKHx1QrIvez+2W46roUPLOei5wVzj7DfP4N2Aoc5t8upnyfOXG1uOkGwv00t8GnG97VvA3vuWAlbB1TPc28jQpNFFETuc559VBb4y36/Vg68t8/kuGWr6e08hJOcTCP+38+bO1MjwL3xltxFvPg7tvZPYv5Xl63R26mDAQ7mHVWsaWKtrBhYe6MDg8vzM0ChQ0FDr+sOKsoctxZLc6UdsnS8RTZvjMpdG9M0H5ysR6VeWuWa99eP7yzdQUA3MH6cQo5qyx6RVHY2lslZv2nlQCKnOGsmhU5w1nlIlcYq8dTZNPWhNB/SDZXMGeeM3Z2z7qB8n0ehSvdUj3PVngCHwN0Z3UQN9FPbZcGly310V0OUysOtjaLrtpyz5pcbqkVuLNKn2ITfPPx/rNCtKeJ4KlpeWdXXw+Ln9N1kZueZ3umFI9tmA6hoADHL/FRzTVgqUe1CRsNMp3V1tbilQncWS0OHk+PW1g8t5nN+r9FfamUSrPqkOnx1I3HUsyzrS7VgweDAqxeFZgQBHqDJiu1hs1JUOSmT6sp6qzKigqRSAr2H0jAHd+fhK7TXL87uCR8oMj03lwkkir86eloDWUH9QxW7qmrjqV6nu3NUj2+1yPAGe8L7PFRHA1e7cJGeizNR3gyCfv2TcLefZMQi8ug6KKWi53dbdQfvxIws38hF7gfFXN3FGEyPcQ1kZueZ3uslNdw2nsCu7mwlQdoOjQ1+bVcXDiczCtsnPzg/gWr5gJopTgy9PalZIpPLR5Pv077v8o14qYo+RvineDkE/09oaAwl9ZDcWHjlAMXnm8vqsalM7GYStP0u55276krxO2uO1rWyLJ6sd4ixaTZvRCzZniG21rp1bJxYeOUC9iaNaPDY+tqn/xLBJWRZokI1daskovbXXe0NBp9o5l9oHZapOyAYfnxS3zU6s64sHHKjQtsRm9oMDz7QpRmVcEZNEcjlVTc7rqjBcs+nsz+exQ5bJGy2wdqFjQQTjs1YH5cQhEa6sUxLmyccgOngNiN3jD/RrnAl1rurdSR28WFyj7s9IFaAZ1RQYBaGveFnQdNjWJJdzlwOHa57BL7Fc8vvRLzyzKYW9pQnNk7u2dREbiSiZt+HDW1ko/FhF00EGg5o7ylilPuBPyC5b5TAzyePv18pJ7iU3DDzu5ZjaR3UsrI7WdWb0Brwi5NAyG9JJkLG6f8ed9q+7MpcYIIxeMpnoCI+05LIm7ojtqd9oH5OFk+PHzSssjpBoK9BEMWOLZoarvEW6o4FQFGb3Zzb6AfT1UVaOWwiaM3x8XtrjtaPHan6mZiZ8IuGgirVvqxSZc4hBYEiOE8Nj62KDcjowD/+CfAo08qMD6RhDLe/V1V2HVOQT+ePvdilEoOm0b0RiWCscj3ad6Z0exuZnfp8hN8PV6vQHwcxdHg06ZIQS5sR8D/B9xB+vfXAX77+8x/UTQvaOBQFKZPC0EwWIqXHMcshnO6d7+9jg90TyfCSqyuVqSxfwGjt3V227IcfXvedUcL7kL4Eov7LuasTpsqDdLKs7W1SGq1jgbPBiO0PzwJ8K9XA3zp5mxhO5p9ByLQ0xeGaJS3SrkZkugNef5vsQCl6gai6M2xj1G9po14F0Ix0HSQ5cMLmrUoDid9LF/mp1JsiLVsoZBQ1SUfGKX19AH88tcAW3dYu20qpWgiFwhIMKUtCF4TwyhJWLyIR4pWwegNc9PjE/ZGRk1OKth76ps9i8pzbzt6czJyu9jJ3tFMZ/WUkwJ9NEYYVXstG4ra5q0CfOZ6Eb7yTcGysGUSi8nQuycMB/uj2kQPVuw7IEIyyezuKxZc6EwC9p5SMhdsR2+OiJtuIpiqaaMJvhnnzfH4a0LCLNK7RWe0tbl6Sz4wUrv+KyLc/n0BorH0fDWPRwRRJDue4+iiXT0T2nQPJqaDCnDVFyT42f0ipPhp2DTz51kfZpnN2+8kaM1Cdq+40TYRzNJQL8KS43zExYBoIExtl6rSGY1EAL7xHRG+drsIQ8NH/5s+lh1wg5dAmIIcHUvAzt3j1J1VnFcoywq88DLAlddJ8NSzAnduTYCv9TXvJfMEcPdCIqHS6FxosNNzyvztetcdLdNYmQjFOO3UAJXZ7GggVNsKPhSA518S4DM3iLBtZ+HvFYR0FEdD5NBVRZGbnKQXZuHuhWRS0UTufx4U4PLPSfD6m9wQKsaypeTrEv729xitzgXLLVlOxCIF/DN2LFvi20Oj7AOXuoRCAv1Rsi4mEgW44loJfvGANQEwRA6jOVKRO9BP31lFkUNDIyUrsO4nAnzysxJs28FFLh+1NaKtYZaZYGkIpegNe07XWLkBU3G7646WFaXYh4DH0XlzvcTmBbZWVdtSly3bBPj8v3m0XJoXc2o2VApvSyMfZzire/dPapEXDfQOF6yN1PYtfPNOAW76DwkGh6jcfcVBaiwA3ejNUu6NmbjppR8lGRtO4ziKebb21uoRNnzT/+9DInx7nXTU32s5NcmeyOFtsdSDVOQMZxVFjpazirk4FM9kUoV9B1S44asifOlmSYtaOUeYN4e8nINi9PZhK5vqmYmbrGilH46Lw4JO7yiN42g15dkSSYAf3SvB08/nfjkcNg5sHjdpOasocoazalbk4gkFtm0bPfzV0zsB+w9MHv4aH0/A+ERCi+QGh1W45gburGaC7wE7awCzoRi9mTYWmGy/+s43taitF+vaJBEGRdEZkcN9o+eeFRon7R2tpuXJWAP22Ru9liIiRVVBkVWw88pJHwsVYscyEk1BPJaCXbutLxfORyjogVDIA/UNPmhtCcAVHwU47yyVOH9Y7thd4pzNpRfVjPt8AqnI9XZ29ZkKXliVb3/UKNiVFWjF940oQr8owBRGj6ex+tTgbgAgWvLikWCwubF6hO3W271aZIXWP+aizIgOHlFFj6AJomzxmIhCgVFcukTD3OOBbgaMjsZhdDQBk5EktRxcJiiY+IWR4a5d4/DOux74XlsQLv+YDy7//6q3kbitVTLxXcXB6I3CSkDNWOjs6ltf7BupR27f+aZWsJuzJlw73ojQLzAQuekdnsGVK/zEotQxVYJq6Bs1hG149OifFQULv6y8LGT9NnYo9HiZgjY6RnOStXWam/1w7aeCcPUnyI9o5cgfnpiELdvIWz3+5ZLacUkinspzf2dXX9HjKYuPo7wPqk3wkGEKbjxUwdyYIjN4vQKsOMFPvEcR+0arWdjAptMpGc6qjZxarsdLJGQtN7bxnSHt11ILGzI8HIf/unMUTnzfGDz3YvX1c60+hcaQD4B3NiWI2yCxldPMrDeq4qZHbT8v9n3pMUXQKitAZQHMcQu8eySJLBrE42g19I2isF33776cwpaJHacTRY7EWcWatp27xmHjO8MwNBTTIje3MTaegM98cRQ+9qlR2Luf5l5id0PraIpdC+gNEd5Ng96rXhDakZulFgltTFEKiBbAoIlAo6atva3yJ+rih8r9v8Ucm3kBsup02nFW43FZczI3bR7RjqHlwGtvJOGCy0bgV7+ujtoRzMmSTOnNpLcvReNsX1TcqOXcCuXazCKJcHhMkVnOOTO0uyZEtikej6PVELU99KgXnv/bkU9gzblUzDuXdpzOw8ZBjn9LySr0H4zAnr3UtiuWhFUrvfCTdQ1QX1fZKY1tO5Lw8OOTxPdTUyPCRR+g0vTTVGgUEs3I7ULSO5AVaMB8nGJyN0JriwSkwlYtx9ENG6WjhA0M51ISTUdZhtNppYf0cEuWKEDmTcbG4tDdPVj2wgYZUdymrZVdHIfb6WmA895icXWYwl0VjN6oiJte13Y3jftKRwe66VBE5E49OUC0BQvSAlnxx9FoVICf3Zf/JKAJkHSsABX8fos9pIZxgM4o5tU2bxllUs5RKvYdkOFjV49WtMDhAhnSXlOD1/8ZpzE+jL244X5j2oMoj3JWc4jcnFmeYVITAYt1A4HKPkrg8/jlr5tzugwBkkzm1w5/v2Tu+8fGEvDWhkE4dKgy81QTYbXiBe7ELvJJIQjuaFBV4kXOHy7kmhKLmx61PUB6P/kwRC7TWcXSjxOO9xM9y7i9qhqKdZ9Z701HWhacT9FiaYf2/UXuf+++MLz9zlBFRWu5qHSBmzeHXp3fwKBMY/R/3uiNxiG604nx4eis4pcoQuz4Bd5hQYAOkvtrbhLVSh8+icfRP/7lyItRxE4ESUgn+E0U3WIEh66qVmhrwkVIdzoIhwtzQZ/sgfPZBgZKE601NfrhxBXpz7DaGg/U1Bx5PhJJBUZGjrizW7eNwt595AlzFLjPXT8OTzzUVHEmQ0szvTfNa2/E/RSMBRyDdF+uf6BxpfdTuA/TSJIQmDfHS1QI6PMK/XW1IvksF5fzk/tyfzCiCEkeEQQTkdmR0g7RtOlglI+gs/rOpuGSCRtoUb4IU9qD2lemsIH2Ojjyb/i1aCHx0ObDYA7uczcQl3C6DjSTaOXd0FiQZeKjad7Ijegqv/NNbcquo/PaTuzybSdd9tLaIjLtcXUD23dJsLs3/3+vIUKSSefTqrOKtWtvvzMMExP0q/mnd9TAKSvbYeECuiY3ChxN0EWtxDo4Wnk3pKc3SRq64Qjy5bn+gVSCbyG8vSVqQgLMnO5ZQHIfoaDQX+ktVniCvOcX5kwEzMdhFIciZ8YqPeysSvmd1XA4Cf94Y0D7lRYYgS1d0gQXfGA2vHf1VJg7p47JWkA8xtLk7h9PVlwnw/Rp9OZtvLs1SePOckZvtl8detGuo7sRVq7wbya5PQ6gbG2RKj5q29UjWV7cYpR3YE7OjMiJQm5nFXNsb24Y1H6lAQoYRmkXfnA2HL+kGWpq2O4hbWqkF5WAnn+7+8cRqvdZatrb6bRiAb2jac7x4yQffcRFu1bAqK2tVVpMch/1dWKi0k0EjNp+83A6aiOpR7PjrNIWNozUUNRYRWm5aGyiG7khjzwe046olQLWu9GEwtH0jFwlISSvGCpFu2YhjdpEEaqixQqjttGxo198VuvRQHdWrZSPYAT3VvcglaNoW1tQO35ipEYqasbOBLMtY7Tzbga/f4y0V9xd0JjOa7B9F5Wj6THRm61Xzne+2TLfye3xNKK2pkaR7nnDpfzpmfw/ppl6tGNuY9JZ3fguHfMAo7WzzuigevxUFNDGiCsmAkraOTcDjN4qKfc2bzY9cRsZVWgU9B5jKtj9WPwK4YVYgkbUVg2lH+MTAvT0Fc+HWB1nVMxZ7e1L7yUgAa/nzDM6tGiNFen9pcVFrr2NzUulkpzTqVPo5d0gLXCkeQfyyE03Eq4mvBDTYDdCa4s0g+Q+2lulij+OIs+/ZC04tT7O6FhnFaO1LdvyDmYwBQobRmusRCUbY7VfPpFrYpB3Q55+LsHkfktBQwPdHOi7mxO1hHdxRvZf2LlCR42EJcd595DUtWHBbqX3jyKYUnrlNb/lZSZHim6tO6uyqmp5NhIMYWtkdBzMR+b+0ux8HG3H1AALeyulLYu2qYC9pqRkL222I26OGQkYtc2f6yUqG29uqvyCXdDGYIuWC20zseOs7tw5BtGY/RdlqYQtk/RU6KNFjpWpAFr0Vh7DOM1Aq1PBIJVSSVdjH5V3s3R13/p6y0wnjYQFnd7dPGozx9ubjiR4rY4wyiTTWS0kckPDMdjdQ7burdTClokhchjNhUJeZqUnlVQSsnA+3WU5A4eUGsK7sB+5ybJ6np6rIJ6jZoZF871E9S/VErUhf3n2WJGws+zF7G273yb7kF3R1eoaYcvEcFZZXVslidtsSsMrDTZvS5BuobEXud1+WzO+yn+u5yqm6GE8M5GbN4dsXls1RW0T4SLLXmSH+vsAACAASURBVAi2U+VyVnf3jGvLXOyCdWy0+0Jp09ZKZ9tTLnjeLTcDh4hLZWZnFvNaidw6M/+gh/GayNHYYJXNcQt9RJnqujrizdZlw6FBc7Y86Xaq9KQPFbZtt//fjUK5amW77dtbZd6cFFxzRQQa6q11TWBzPismJty31csONNuwDGjm3ayI22W5/hJFLplUG2RZpbKmD2lsELHBfaHd21dLXZvBu1vMHw+sjjDKvm1P7zhRexVGbKz7Q7NBgbvlxrAmcmZpbPAzy7u9+npllIR46Gsb1ruRWtXWxE0/kt5R6Hu0NX1JlWhNn0HX8T6iot1q6UYwePk16z+uHWcVp+ji/gO7oFgsWkBvZpoVBF3k7rhtHC690NzLk2X0Vglg+RBttmxLki5tthy5dZr4Hg1ZVhuSSTWoi5xlSIt2cfJHNUVtScL0jRVndeeuMaIx4Ri1OdUAnw8cnHDyiUlY+7VxOG1V4Qhqziway9E5VhgZIx66MMf4jdlXWs4jaSFQ5Ow4qzOnS8Mk5R84+cPubcuRVIrOp6eZ5TAkURtSqqgtF14PwIXnx+A/b56AZUtyO5hofIRC9I/Qp55cOQeLlSvouso4AolwI/3hToWi4mbmSJoPO87q8Ut8RO+ghvrKn/yRyYGDdBMf+ZbD9O0JE0Vtc2Y7N7bICsGACh+/LAo3fTEMs2ce69YtXUy31xUXOOMXJz+plErUqGw4pmZebVNJ/x8ynVVVhbwuKBoJPq8wJ9+/FwOn7Fb6vDanyHZW+/rICnZnTHd3/qqlWYFrr548xllFUaYZvV1/bWXl8dpb6bsKtEwFM1LwIcIHOowucq35nFVSI6GxoXqKdg2sOKVWMZzVeFyBwSGyeWTlkpzPdFYNkTvlJDqlKx+5KFBxUVtTI/1ogpapYObK/oPwgY4hn7NKYiR4JBis9N0IpeIA4TijcnMdDWf15uvDmrOKubcF88myHYsXeeC2L5MOvqgOJiPEpkLxY+nttzU3suwlzXRW583xjJMYCQ0NIvftGYG1bSQ0MpqywRrDWcXykes+Uw9trfZMeBS239zbWHE7TEErlqcfueHwSkJMRW5nUr/yHKDILZjn3WX39lj+UROqnvIPJ5mMpGB0jMyAdmpOGytQ5NBZff7JOjhuobXo68qPBytW2JBgkM3PpSgwTHBzLXIrlrD5KMEDmMbnFfATIOfuQTMEA8K4KAIXNwYcOkQ+PZbV6G6nQWf1yYeC8PDjHrj7RxPafLZ8nHOmH67+RJA7ozZRFFW10wuto2lJXnHTS0As17fZYdEC724AmGv39tVoJDjFoUFycXNjCQgJl17khUsvatYa4F97PQnjE0eOUUsWeWDVyb6KjdScAh3TNvtOrJYgLRS5me5KIGXhfK/tVwL2kfp8QlXVtjnJAGHk1thQuZ1wKGT4xaFPMglEIe/O7llzCn2k5lx0SpuaGhF8Pvu1bQ31Ip0lmZxjwKLdSISsv8vrY9BdzXENtMceGVCY7VZQ3K4ivHNTzJvt2U1y+5qQ0OTEdVYjo6OVMxKbU33kFLfbb2vGWHu1E88GyZEUB1KymEzASTNAId/G4diBwuDK5fkiN9vHRCuQHkmraSBlPqa2s1v0S9JLyuGUmLy9E47k28iPpLy2raWZ3VTX0dGqGrDCcRmkW+jzidv7nfgxZ8/02J7c6/cLe3iTPFgen22FZJJdVMjhFENRiIbeHhu5OVXfRlq4W1sjtNK9ovIkFGIYuRF2JgA3JTilI2fOzZGasfY2shIBfiRNEwi4e9kIz9tx7DI2TrbHNJe42Y6mrLD4OO+bdm+LE0D4kTSNoB3v3X185NEbxw6yrBJ9cueSiEuc+J9obpSm2b1tXZ3IK0MzWLnc3Yn/EW5McEpAScQNB9yJItgWt2CAF+5mMm+OuyM30hYuDscOR4mbXrzLbH6bwYwO+yUgoggjfCjl0TQ1ujuvRWOyCKf62H9AJpnueUZ25ObIqFCSEpBQUDC/WbdKwPxjvg1ObkCbCcfzbhUJ7kVhxeCwTBTFZIubI2YCSQlIKCROp3s1lcGZ73N3XmvrdtufZxwXk3JxRiRb3N7D+gFJS0BYTSEod1i2YdGgp3eCl4VwHCVb3FawfvDZMz2b7N7W6xX28RKQ3ODzct7ZdI9+tBcSv7OJZHI0h2ONbKlg3pkwo8Nj+5AeDAh8MmABTl1J92haE6I7Invb9jGee6swWObcSDksbrff1uxIxb/fL8yye9tQUODjxAuAM/5PW0VP4FiMB3/t9QHq98kpHcPD7k01ZL56G1k/GNa3kazvCwR4vq0Y56yhFxmxWMmH/aqvvNpP/X45nGwyxW0R62eHpL7N6xF66V5NZYLRG63cW2MDm61Ve/aGYUP3ECQS3GAod2LxMjiWAsB81g82dao0Yve2fn/RNYQcnTXvjVMZhVRTw+4p37p9FLrfGYJDgzFIpbjIlSu9e8h2bLAkU9yWsX6whjrR9sQRXt9mHjy8f+Ezk8T3g5Eby7V8u3aNw8Z3hmHv/kmt/1RRLEYB7h6IwiktvZmvXOY9pV6vYHtdoI/vtrVEXa0Kl15I3vbU1srWZ8K9qJu3jGq/7tk3aanJPiVzdSs123a4tjOmJ1PcmPaUkhTvYj8pXwRjnZUnJonbstrb2Jvo4+MJeHvjEBw8GIHxiQT07Z2EibB728k4R8hcSO02NHHTG+aZMqVNsm8meIUwfz1ZBz8OPnZZlEjgOjqI5gWaRpZVrYvhrQ2DMDYWh+GRuHZcjcb4qHO3org8VWqIGvOGed1MmGvntn6fwDPONkGB++ilUejbK8HYuPX8WU3Io22NpzFy3AzxuAybNo+A3y/BjOk1WpGo3ydCS3MAfL6s6yebZcghJJFk+/y3Nkuq/hK2hfFqYb6PoK7G/oDJQECYTfdqqgtszbr5+rDtCG7ObOc3KKLI7dw1Dm/8cwC27RiDHbvGjnFWPSbMjs3bBBgcYnyxVUo0ylbcOqZJRCc249Uxg87l5MfvF7rs3pabCeSgwNk9ojp1NM0FHlcxF4eu6st/Pwgvv9qvTRix4qze8FURvnQzRq5OXnnlM+HifBsArHekDb0p73pUc3AzgQ74LH78sqhlFxWPpnNm224soQZGcyh0G7oH4aFHdsGu3ROm7hpPr0MjKlx3kwTfvluEJPcqqLDvgHtr3CAjcmM66sjrtS9OvDOBPiefmISbvhi2VOi7ZHGz636OaLT4m0vNyMvh7ze+C3D1FyT42f0iT9kREp5k+wRKkkBlWOVUOpeTG5IxRx5v3sXRHAJamhUtD2e20d4t0ZtVIpEU9PZOwOjYkZY0RVXhhZcBPvk5Cf7yrMBFziZvvMV2wktDvUhSid7jiHA0Nooxu7f1egT63dscDczDXXh+TIvizKwHdGP0VgzM2R04GIEtW0bh1df6YdOmYdi7N6zV1mEk98CDAlx+rQSbtvLUhxXcXgaC4maUgjDtTiBxSvmYI/ZgFPe5qydhd48HHvxDIG/JCEZvSxY3aaUa5cr4RFL7gn2TeOyB5qYA1Nd74RvfDYDPK8EdtykwczoP5YrBugwEEQQgshKNVzHT7gSfT5hn97Z88q4zCNqKwBTccmO4oOGwdHGzVvdWCWBUh21fWsnJGwOwecsIfPoLMbjpPyQYLl/9doSBAfbF1aIIJEeFDY5IB8kMN77Gz1kE3XC447bxvKOTTl7ZzrShvlSMjMRhx65xeOyJfvjgZWG44lqFO6t5cLtT2tnVN8r8FUraU0r1YjhWnns4871x+M+bJ44xHXBayPITmNd9lwwtojsUhZdeGYKTTh+Bf70qwU2HLA4yjtwIy8e0VWuiU+PF7SCJAi+7LDE4/BJNh6/928RRpgM6pwvm255gVTbgztU33hyDpauG4abbYjA+zlUO2bKNbUhLUj6GR1LQc25sxq3qkDTMixIvA3ELOELp2qsnj3JWMXorx/IQO2AB8SOPT8DJa4bg3v+xbf5XBE5M350z00Ny7h2FHNuvqFNbK9reCMIb5t2H4axec0VEKwI++aT2qhE40GfI3fG9CTj9/GF47Y3qTMiNjbF/W9bXiyTDCLXIjfmoo9pagcTODVC8FA4lMp3VTVvwJZQ2GLbvqJ6t8vsOyPCxT43COWf64c61dVBfVz3G164e9qJeVyeSPIgzkRuvcatc8O289LiU5qyu/VqNFsVVG888H4fTzx+Cp5+rnn2sO3axd0q9HoFE3A7n3DgcItBZxfKRX/0I4Jqrp1HfVO92JsIqfO7GcbjptgkYn6hswwE7E/buZy9ukgQkgU0POCFuJKOOeAFveYHO6s3Xp+DZxxurwknN5pHHY9pRde/+yp0ePDbOPt9WU0P2xu/s6nNG3EjgBbzlSXubAE897IMf3NmstWxVE5u3puCCy0Zg01Z3F7napc+BVX41IaL3fbfxGx4bcZjxofdLcNe3p8LSJU0V2dGQDzymfuzq0YoUuLffZT9unrAMpMf4DdNXHOmQSk75g5/Bxy9phgs/OLuqRK4SBc6pfNuUdqLx4huM3zB9pZFUGUsS9FO9GE5JQVGrNpGrNIFzIt+GBIMiifXsjLiRIApCdZeBVyiGyH3kw3PhlJXt0ObAXtRSggL35QpxUZ3ItwG5U+p+ceNUPnPn1MFZZ3TABR+YDQsXNFSs+YAmA5aJlDsvvco+3iBNZRlOKbAWt/o6cZjl/XMqg5oaD6zoaoULPjgbzjtnRkUKHRb7/urXJB1FpQX3xzqxXX7aFA9JiPtC5h+YvoLaWqXtALCK5WNwKovGRj+swK+uVpicTMG+/ZMwcCiq/Vru3P3jSTj3LB/M6LA/BqxU7D/gTO3ezBmeSYIl8Rsy/1BdRUicsgIjOozi8AtBkcOv0dGE9msyWV5zFTD/tva7k/DTdc4vuSbln93OtJfpS2G4uHGqi/a2oPZl8NwL+7WhkuUEHk9xmsiqleWzaRxLQFjPbzOgZSaAnnMjWlnPCr7Sj1Op4PG0nHCqBIRkajdeZmdX39HiduvaYVcW4Xg9fJYbh5y21iB0TKtxVV0dRm7lVPu2ZRv7rgRk8UIfiR27IfsveHTEqWja2gJw2numwsUXzoXVp07VBmu6QejKyTld/5IzJafNzWKE4Obrs//CtTk3RVF5PpBDlekdNdrXySeB5r729E7A/gOlOSLi/LfxL9e6fsjlyKhzB6iAXwgR3PwYcTM+wl4huFMmxONQmWMVOK4ARQ4jug+eP1tbNO10NIfOaTkMuHTqSKoX79qevN3Z1ZdX3N4guTAOp1zBYmFcNP2hEojcX593RjhIcOpIumCelySY6c71lzznxuHoPa+GyDk1aPO1190tbk4eSWfP8pAs4DgmaoMMcdtIcMccjmuRLFYXoMjhysJzz57BfFw6Hk3dvEFr/UvOmR4ej9BCcPOC4raD4I45HNcye4a9tiHcqv/+s2dqZSQsedWl0RsW7u7uTWGSn/ljzegg+xDp7Op7NNff82Mpp6Jpa7V/tMIoDk0HlntZN211576FnbuTmsDJCs5XE7DulNljLV3sI2kkeCHfPxjidkwBHIdTCXiIhkykYbl4ep9Ll8m8/tYRJzeVSo9URpFjQVOjSJLcyxm1AevILZVSbb8ikil1Nt2r4VQjHkoDOFDgWBxRN7uwU2FyUs05BQRFzuMRoK6WnmxgCYggAMkkgZz5NjDE7da1w6MEd56X3j2pJSzul8Mxi9dLbwIuTg5mYTK4bRXgO5vz5wEFASAWVzWRqyVcwQfkJSDH9JNmwnNuHI5JMAd3CoOt+vv2u6eNGvNsf/t78do2FLl4glzk5sz2krRc5T2SQpa4/YDgQZiA0z85HDeBOx+wGb9S2XfAWiBliJzfL1h2VnH5siQRHUlNi9tBggdhQoo3YHFcyNLFTVQvatMW97zQn33BXkeC4az6fead1aWLiI6kUCjfBlni9nfCBzqGUQcrnDmcXERj9B0+jN5o5t6c2E1ghtExBQaHyPJ/inrEWS222pPwSPpYZ1dfQa8gU9z2EjxQThJJsmNlJKry3aUcV7JwfmPF/cf87RV6faR46lJVyOussj6SQpa4DRI8ECv47lIOEZEIG88M58RVEvG4Clt30G0Fy3RWQ6GjozgKR1Lz4saqHERR4IDd2yZTKndzCUgksPkZ4N0tR75GSdqTy5CxcTaFp9ieVUlb8zdsZNcGhiKXTMJRzuq8uV6SwKXokRRyDKvEuW6rCR70GJJJdcDvF6bZuW0qCTxpZxE8CvzlOYCXXwXYmqdjWJIE+OC5AJ/4F1V74VUyvXslOG4hmx8QBe7QYPnuIjUwW/5BiuGs4q4EQbC94QrMRG2Qo87tCdo/kKran/YrK2r57UArIe9sEuCTnxXhgd+JsH1XftWSZRWe+IsKn/isCM+8UNnqJjOsj21s9LG7cwd5t0DRLgtOWOojndJpS9yoO6YHB2TbTbGKAnQ99wrm0Scl+N7/lUCUBBCFdHSGx4B8kRlGeLj38xcPAHz8GhHe7K7wEI4BtI6l9XWlO95i1PaX55yNPttaJRKn0dSRFHKIm+sa6BMJXshbjD/+2QNP/lXSxEwSUdRE7VdB0H8v5Rc5RVE1kbvzB2mR6x+ge20H+stvu7pZakJ0do8uOa5060KcjtoWLdD64UjcGFNRG+QQN+rp5j17U6tIbp9y59AE17B5mwh/fsYDHozYxCNihl9ej6j9Xebf50PWRe6GrwqayCUpGWcs6szcQg3jYZaswej9lX84u8dh0QLvBMHNsZf0PrPffJS43bp2WKW9LIa01i0WU3upXUyFgUeK3z3s146iAgqYpAtbpsiJusgJaZHDoxT+mg/Mx6HIXXmdCLd8g57IcfIzvaM0x9KevhRMhJ3z7GpCAvi8AtPatkxyPatUTYWBQ2ShVzzBy0Hy8ZfnfDAydiQy06I04cixVMoQMy0HJ6VFTovqiogcCtyunrTI/c+DgvYpX46Uw3XP6HD+6I4fjA8/7uxaw5Ur/KRhoumoDfKI21OEF0CVVEqtDEuKMvjifOYF32FRQzCC83iPPooeFraM46pHz8EZf19M5Axn9cFHyu+IqaoqpGTFtSK3eFFpjrZO59qA3EjozbW+rxC5xG0LwQXkJB5Xc67eMoMswxTa11MJbNuR/rTPFCnDNECRk/DP4pFj6WFh08UMoziPRWf1D0+Wp7OK148Cl5JVqiKXSJIf6aaXKGpz2iGlYCSss3qDY8Tt1rXD+FPvIbiIY5iYVIjOprEYd0yz8fnSAmXIDAoTCpchUoboSfqfJSMnp0d0+H1ihrNqHGcLiZzhrH6XkbPKGiOKQ/OExitqdIw8Gb9kkfPi9vqbzi+DPn6xj/QMbCnfBgWGVf6Y8EKOYnRUIWrES6bU8i8DZ8BhQcNjpn732eUf+GeM4jSRE+HwsTTbWTUiOivlI4azOuls6oYYvP5UStF+LTWnnuxs1gVnJL76ekwbTeRhuPQlk7ZW4o6E+zu7+nqs3iifuFHNu5GOG49EVTc29ZeUhvojRyJDkAL+I1eUXf5hfE+ms+rJ56xm5ezyYTir19zoXmdVKXBy1MpfCERudJQ8b7VqJZ1aObO8/Gq6zQp/ZgFUCAbYbrZC3nOKf5zwLiwZCQb5splU826TEbJPyESCmwrZhELHPqeyLILXk37hyvob1hAqFCL8e+PPivbndDNz+oUOh79Pu52Q/nuQ0tGecftINAVDQzGYmEhCNHpksMOrAPDkUx44ZWUA/vu/AlBf7468HB5FUYAlPVrNBT5XiqoedpvNEomQqbnTZgJO/shukMdIDvOQtTUChCfpR7IUyj8sGwkGOSM32nm3yUmyxCs3FY4lEMj/QhT1CMyfEcllO6OFnFUsE8l2VmNxGbZvH4PNm0dgYCB6lLAZRCIpWP9iGN53/hA8/ZzzeZ1CGFFmvigN3+D4PVac1dExssjt3DOd/cx+7E+58wdaQzuOJpIAQpTX9512aoBkICXydbs3LFRD9k27d5oLEscUuKlwDPgSnD2zsE+jaJHcERfVrLN6dPmICMNDcdi4cQjGJ8y9mTEC+NyN4/DwY+4bx6cJWIGjqFln9dAh8jTwuWf5TXwXHQ4NynDgYOHXS3o0UVrkamrIRQ6jtvo6MURwF2N2jASDQuJmKxTMx+CQTKROfCrvsRy30Ny8v3R+7WiRy+2sisc4q317JmDrdnuj/r78HxPwkgOjdAqh4qEh65V3OEpL5RewYs7qAOGoo+nTJFji4LH0j382H0DhayARV7WFL36LS18yoRC13We2ST4XhcRtJ+GFHcX+g/IskttHYypfF5PFCUvM53w0QZOKOatw2FkVRYCD/RHY3UPSCgjw2usD2nGQDcU/L1GatEgNP1uPEbn0v8kFojTDWZWzIr39+8ks4nPPcu5IintI7bRZaXlWWdWdVWu3pRC1gZ3atkzyipveZ/oQyZ1nMjQsN5PcPplUp9O6lkqhqdH6C9YQtMzlHbmcVSxQ3bKNfDgzCtubG9iY3VaqJwuVfxwWsCIiZzirk5EUcb7tqk84sx4Qc2nPrieLMg3DCZ1Vs+UjFKI2W+UfmRTr2/wWyZ1nMjKqJWqJwgCedzsajK6WWYjejkJN59eyy0eMntNtO8a0NzwNenonYHKSfuBtpxQXI5FUHmPBTP0bRnC7dpMNz8HyD6f6SZ99gV6JKB7jsXyktkg+jlLUZqv8I5Ni4raR9AEyicfVPpLbhyO83i2b888mcyVl3XTIdFbjcRn27rU9YzQn23YwWdFRFBSqnEImqyCnFFBz/FsxZ7Wvj+y5ufQiZ5bL7N2fgu076RcfFnNWKURtL9gt/8ikoLjdunY4RXME0t79KSILJhola+OqRJqblaMKeu2S6axu2TpC/Zkizd2RkK9Y1zAW5DzGQi5ntW9PWKv1swsaCZd+mL24YQ3jX59l19iTz1mlFLXZLv/IxMw4oe/ReCCg0KmA9W4YGnOOgC+rf72EniOJpkM0Sv8zBCOhfYRJeFJQ5NABVdRskUtHcblELttZ3bKFTPivv5b0fW+Ov70SdWRWW7azunqVO6I2MClu1FqxSGe7Qdo15X2mWcydk6ISvbFm7z7K4mbicy6vWOUo1jVELp+z2tM7XhZRG9a0sVzVlwt8TutqBGioL61DmklRcdO7Fai5prGY+i7J7cOTPO+WDUZvV3yUnubX1LCpv6JR+GoVwyTIJXL5inVzGQsYeb67yf1RGx5HrdS00eS0UwOkPaTYamW7aDcbs1NuqbmmpHm3eFydWagZulrpmCrbd06zCDHaDaCVUIw635alCVlKyVm0W6hYN9NZ7X57iMg9RofUiajNqeNoNq0tEpYXka7ipJJrMzArbtRcU9K8G2hvEoUfTXPwL5dEqRxPaW11ysUIhUkadilUtFuoDGTPnjD0D5BFQ7d+mWTijzlKcRw1WL0qQGqvv2Bl+YsZTImb7pp+lcYD0si78aNpbnAiyDVXkB9JWC4bHnD4aIrFydlkFu1mk+2s4vQT0mLmL30uxLzVCsdNPfpEaQybxYt8KuG8NqAdtYGFyA1o5t0mJhSi/aj8aJqflmYFPvmvZALX2MCuoZvmsdSMbx4ISHn7Q42hm7miNbzNyFgc/vHPAaLjKI41uuoT7HNtz70YhUQSIEh5qkcxsNNl4Xwv6X8qNYc0E9Piduva4R20xiDt6knNIb0PfjTNz9LjUnDphWRPT8e0GibXRtq2ZId8/aEGuerZ8M+bNo8Qd2l8d20d1NexFZxdPSnYuTuplWWkUukZfVhv5gSnnKRttCJNJlKP2sBi5IZcT+NBe/emGknvgx9NC3PyiUkigWtvY9f7uHPXeElGfCsFJu8eqWdTtKPoK6/2QzhMZtB895t1zI+j8YQKTz1zdKSu1Z4lQas7I5nqUYyGehGNBNIwn0nUBjbE7Y80HhSHVyYSKlFTLB5NeUFvYVDg7ObgOjrYRG7IvgOT0NMXhuGReElELl8xL+ijw9/acIg4YvvIRQFH3NEHH86fZ8PUDX75GO1LOP20IGnpB3IlhfvIiSVx042FH9B44L69KeLM92REpd8nVGHMm5OCr/3bhGUXtSbkgbZWNtFbNCJroobitmfvpBYpOU2uYt7evgl4+50hrfaNBMyz3bm2jvlPhLPywiamXOPPh9GclakexUATQRSBtPSDePJHIexsc/82jQfesStJXBIyNq7wbfQmqKtV4ebrw3DaKmv5rjmz2bxBM6v88ZjYfygKvX1hiMasOelm3qaFxhiB/safjCShe+OQ1jdKCgrbb+4lzroUZd+BFLz9rrX/z5ScFrliUz2KgQ3zC+d7SXv+cLTKDYT3URDL4nDr2uEDNJrpcQSSosABkvtQFGjgY5DMgeORLjw/Bjd9MWw6ikNxY1HQm0jI2lcmKHLYe7rvQMS0yEk5yjyyMQp4c4kcRmg4/eStDYMwPk5udBjCxtpAiERUeOxJ+wefeCJtOtjdl7B6VQCFjTSsX0cyZdcMdiOfK2g8+N59KeKPyrEJheoC6UoHS0VuuTGs5eLMiNzSxUQzRvOCy2RygYtnUOSwHo7WPDnIKtI9LGpvHaLW7+qUsKEb+vvHyK9Zm+phw1mdO9ur1tSIpMlEbLNi4pBmYlfcdtIoC9m0NbGA9D6iUW4sWEXQc3F4VC3mqLKK3oo1oI9PJDXTYXAoRs10wGhxT4ao5SritYNTwgb68EkzeTazGM5qIFDcWcWathOO99Go5WF6HDWwJW76CPLLSR8cj6akrikyEVbJRqNWKXhURUf1jtvG4bwCQy9POamd+hMUNmkiYF0cibMqy4q2Z3XnznHY+M4wHDgQoSZq4LCwvdkd1+rZWCDLaWcVBS6f6XDGadpxlEbpB7Xm+EKQJORfoBG9bduRJH6ljU8ofGkzAShyZ743Dv9580RO06GtLQgL5jdQfUwro4NInFWsqcMx56Nj9Bv2sdzjif+/yRFhAmS33QAAE3VJREFU69ubgldfZz90AAUul7NK6TgKLEs/srEtbrSit129qbmk96GqEJwI844FUoIBVTMdsHQkeycq5t4aG+h9hmD0ZHU2WqazenAgCslE6QYz33pTrSPlHpCuCoAnnnJ2jFGms4rGwwnH+2go6zdYln5kI6hm12vn4PbbmlHaewFgJslFXHBeaENdnbic5D5EEcZmzfDQDS+qnKFhEX52fwjGxtOfgRj9rH9xP9VVfT6fBH6fuc/YeEI5xmV1Ghw4+ZO76x3bOYoGws/uo1Era5+zzwhG/X6B1B1FE4G47dIKROIGaYFbAwDPk9zHjA4PvG81ecTb0ixG62pFZ3amVQmqtv/AAw/+IaCJHAuBKxeu/HgQrr+2xpFjKOjC9puHwlQNBKssWuBVO+d6afzAZ7Jqs8oHjSJY4twbbulRVSAvCxlTSjukvwIxnFUsH0FnFSeGnHxSu7YCsFrAaA1Ng9u+XOuYsAEDZ9Qq9XUiUBK2u50WNqARuQGl6O3ELv+eRQu8RMdbZGq7pNnaHDZgwvmFV/zw4CNQ8RFcXa2gLU/GaM1pUNhw2ge+Pf0+rdXQ0SvwegQ458xgmMKcNqxkmMO6YDcXtD5+iaO3rTuSxMKGDA7JfFoIQwxn9b/vSMBVn5xC1WRwE+iEvvhUS0mE7e//iGvCBhl1aOhcBh380D7t1ECMgrAhV5ZC2IBW5Abp6G0+AGwnuQ8axgLw3Juj7NsPcPnnYlq5RSWAooaLXJzaCJ/Nlu1J+Nsr+ds28cMFE6E46ogVFPNsj3V29V3M7EKLQE3cIC1wL2Prmd3bt7dJ6MwQXwd3Tp3n4ceT8PVvhfO2VbkZ4/iJI4pKJWpgQtgykaS04UC7OwfzbO99D5VRTSU7jhrQ9rM/hI0Hdm+M+xWwY8HnE4gsY2yox7o3Hr05x6UXeeHcNY3wo3uj8LvfR7BrxPXXrG2kcmjuWjGsCBvoHQV4ZMX8Mi2Rwzzbaadqi15oHEcvLqWwAe3IDdLR21cA4A67t58/zzt88ol+4m5tQYDYzOmegMiHIjnO+IQKv/p1BH7166jrRA7bpVDQzj3LV9IoLROrwpYNLdPhnDXBiM8n0Fj4gO6oI/2jhWAhbhgN7iIp7P2XS2r7JQmmkF5LQ7041tQo8uNpCfnop4T0KKP9panSwSPnqpN98P4zfbDqZK9rBM2AVNgywbcybkCL2hgDdtqqQKKhQaThDmFR//JSR23AQtyAQmkIregNtAJhicmIZY45fv5ADezulbSSEZzEgaOMcPP8pEO5OaxPw+OnG6EpbJlYjeQ653rURQt8tN4kKzq7+oi229GCSQ/JrWuH199+W/Mrds2Fvj2p5pUr/BOCAMTNe4PDyuDUdqmV9H44ZGDR79w5ddoXaHs0Ulq3w8hoXPs9il1kMmlK9LD8xOuTNJEsV1gJG2QtiCnmrKKBQFHYbnSLsAErcdOxbS4kkipOCxldtMBLLG6xmNoaiaiRUIhKLoFDiZoaj/Y1nWARzYO/31mW/x0shS0TY7cvLojB32ebDrozGqOwmg/0UUbrKNwPNZil229dO4xn7o/Yvf07mxIzVRWoFE8NDstJvsSZ4wacErZMjAUxgYwxRuiMrl4VGKckbFj2UbJ6tnyw9hIftbtvAaO3t9+hMwICS0OGRxXeucApKRs2JhwXtkxk/d2E+0bPPD0QobC9yqDkZR+5YCpu+sy3D9m9/aatiUZZhn4a1xIOK618mQynVPz1uSi8/ib7YZPFwAhu2VJfwuOhlqa5sRRN8WZgXgVGejx9sztOzerifaccp8HJ6OtfisL+g6mjjoWlYtVKf6K+jkrJB+jtVa7Ks2XiVIkrHk8fsnPDHbuSzbSit5QMreie0rgvDqcYeAx8+LEw9PSlHeD07gbV0rYpmqxc4Y9TFLZuJ0eG28ERcdOPp7bXAa5/KUpc0GvAj6ccJxifUOCRP4aPqTVLl2mo4PGAo1M+5s72qE2NIulyF4OxUk77MItjzUm3rh3GoqQT7dwWe07Dk8puWtcyMCiPcfeUw4rhERS2yYJFtChyuD8VRS7EOJJDYZs/j8qUD4Mr3VTPlg9HOy9vXTv8FgB81c5tn3sxRrxIxgDd04FBnn/j0GfbziQ8/mfzrWbacuSkCgG/oNWj0YaBsH3DqdV8pJSirfzbdspDJicV2Lo9SW27PBb3jo0rpfPlORWFYRy88pq9l5SsqICtkH6foI0zogEDYbvfiU3xtHBc3PT82zl2JvdiYS8tcwHSS6EDCYZD/zjVAb6GMo0DEhRV1QZSpp1V+3fEQNi6ndoUT4uSDATS829nWb0dJmJffSNGdazDwQGef+PY52C/DL/5/bHGASnorOKR1Y6zykDYcNLHGrcbCNmUbNrZrWuHd9ipf+vbk2odHlF20boOzL8dHOD5N1b8n4uicGKXtS3x5cJr/4zDU8+yXZZs1VllIGxjbu1AKEZJRzneunb4DwDwA6u3e+nV2Dx022ldRyKhtg4MysO07o9zhKZGRRO4T18egbmzS7tQmRZ4DH3o0TBs3ppw5PHMOqsMhA30iM31zmgu3DCn9garBb5oLnRvTFA9TEYiajOOJqd5n5wjzJudgs9cPqmJXGND+eYBWB1DzVDIWcUCXQbCdlW5Chu4Qdx0g+FjVg0G7DulWfuGDA0rQV7gyxYUuS9/KaxFc+UkcrinAN1Q1sdQM2Q7q9hSRbFA1wCF7T5mP4QDuGLDwK1rh9FmWmRV4PTaN2rHU6T/kBzlDip7MA/3pWsm4ezT4xDwu/v5HhlRtNo1LCZ3E6KkRWw0e0UNvlHuwgZuETc44qCusnIbPJ6+/mac6rxqVYXggX4ucE4QCKhw9hlxLZJbfYoz+Ssr4By0N96Kw5+ejkA0qkISlyNLglamUWqwAf89pwQmGQhbWdWyFcJVu6FuXTt8AAAWWLkNNtbTdE9BF7iBQ/IgLxFxBhS5C86LwU1fDLvGWcVo7dEnJ7Fw/Ki/x7yXnEqLXChYGpGrrRFh9SmBcUkE2uvwUdhc3QxvBdctvtNLRCwJ3PMvRufRLO4FfYLI/oOpYS5wzuEGZxUnefzt7zEtWosU6Q3FSA7zXizapvLR2CDiUTRGcdCkQUUJG7hR3MCGwGEt0NPPR6hNDjFIpaCZC5zzlMpZ3bMvBb97OIy1lKZvg68NVUnvKaDVNpWPWTM96vJlmm9Ae4t0xQkbuFXcwIbAjYxq5SHUCw25wJUOp5zVibACf3hiEl58mWAxsgIgCoJWpuFhIHInLfcn5s2mXuoBlSps4GZxAxsCh+UhtPNvwAWu5GAeDkWOtrOKET8aBo//qfAR1Ap4rBUEevk4NA7etzo4WVdL3TiAShY2YLWUmTa339Y8HwC2m7lbn1eACz8Q6vH5hDm0r8PjgeGOqZ5m0dUfCZVNLCbAy6/54NkX/ces9sPly3V1IixZJGnLuGdMl2DxIg/U1x0tNPiS37k7Ca+9wXanAT6OzwcQidp7j2F+bfkyP14k7Ro2qHRhg3IRN7AocE2NIpx3dojKUudsUOCmtkvNfIt9aRkZFeHhx2OwbImQU8Dy0T8gwzPrnW1EsSNySxb55PY2Zlm8ihc2KCdxA4sCN2umZ/C0VQEmm+YFAaLTpkhBJ10yDhkoaq/8I0bt+GkHfKth4W2hGkr80Fx1kj/i9TJbIl4VwgblJm6QFrggAGwFgJnFvnfJIt9o1zJfI4vrQIGb0iYF3VDQycmPG0QtG0FPa2SLHONjKOidBxVRoGuGshM3sChwa94b7Jk2VaKefzNoaRajdbVikNX9c+zhRlHLBg+dqZSKNZWw4gR/vKGeen9oJmXfK2qVshQ3SAschkwPAsBlxb73vLNDu5qbxHmsrqW2VhxsbRaZHIE55sGX8v4DMu661UTDbiLfSWpqRDhhqW9CFOnnhzOoOmGDchY3OCJwnwKAnxf6PnRQLzg/tMfvF4pGenbx+YTBqe1SK3dSnQfHAO3ZJ2tlHZngSxtnoLl10suiBV65tYVp6e9YOc9jI6Wsxc3g9tua12AXVqHvcULgRBHGprZLDdxocIbwpAIb301qnQWFwJe41wta87sbwGit63jfuCBQb6HKpFefoFuVwgaVIm6QFrhpOPm5UB4OBe4jF9WEBQFqWV5LU6MYa6gXabfIcPQi2d49Kdi0JWH52IlRNXYSYPFuKUAntHOuh3W0Bvoyl7LbeUCbihE3SAsc7gv6TaE8HMsauEwkEUand3ga+TGVHHyJjo4psGVb8SjNDNpkD1nVhNIpGupFOH6JL4wpWsYPWTWlHsWoKHEzuP225ksA4JF8/+6UwKXfPCp0TPOYXvDBOQIeOzGXtvFdNrPe8IMHjQeWIuf3C7BsiS/m9wtORPI3dnb1rXPgccqCihQ3MHFMdUrgkP0HZYhEFEwgQ8dUD/PpEeUKvhQnI2wFLRdej/0WqXxkHEHxB2FdKoTGwZXlsgneKSpW3OCIm4qfZF/K9e9OClwiqcrbtielsXEF2lqx59ELrS1S1Ud06HSOjCmwc1eKypHTLjSd1RnTPersmZ5JB46goOfXrqxm4yAfFS1uBrff1rwCAB7LFcWhwJ17ZqhfkoD6PLhcDA3Lyo5dKRGPQwiualvY6cV2MW3CqlDhWodHwPEJBZdhw85dSdfVopE4q5hXW3KcLyyKjogacj9uj6t24yAfVSFucMRs+H6uKM6JMpFMVBWSu3qSnoP98lFShsLW3CTBvDke6JiGUZ1Y9kdYIzLbt1+GfftTZVFYCxadVRS1xYt845LEtLQjG55fK0LViJuB3nz/XHYU57TAQbq3cHLbjmQNHlUzQZHDWqh4PP1/s6DTC+2tEjQ0CNpYay+TmYVkYESGQjYeVnBFIhw4IMPgcPkvYdYiaTW3yDlsFhhUff2aWapO3KBAZwMK3OpVAaa9qLmYCCuxrduTAUPMDFDE8CuZ443V2ixBU5OoiZ7XB1Bfm47yMJHN4miL4qUoaWcRBSyZABgYlLUx2zgbrdLJdFYxUlu00Dvi9QhNDv/Y/BhqgaoUN4Pbb2vGiSHfyD6qsm62z8dEWIlv2pL0G/k4AxQ4FC6rJQuGAGZjCKJBOKxCdvSIWDlGtrdJrtvrSZv6OhHmz/OEPR7BqZyawZgualXXH0pCVYubgX5UxU/F1cbfzZ/nHT75RH9zCS4nPnBI9uzuTUnZIofz+UGwLnJOgc4vtp7lEspypmOapE6f5plg3C6Vjxd0N7Snop5UB+DipqMfVc8AgAeMfBxGI2edHnSkVCQHsWhUVd7dkghlHlfxyBkKiQUHHpYaQ4Td2rBuBsxtzpzhkZubRCzpKIWoATcNyODiloUuchcbHQ6Y2D/vrKCjRkM20aga2bojGcIN+wYocsGgmDMf5xYa6kQtER8tI5HD0qDZszyjPq/AZMipSXjtGgW4uOVBLx3BHr2fl8poyEaWYXzv/lTd3n2pw5ZBtrPqRtyej3NJlAZ6bm1dNU3LZQkXtyJkmg56Hs5T4jcAEhufUIRtO5J+Q9QKOatuoaVFgqEhd4gcGjRT2kuaS8uG59Yow8XNJLrIPdnUKK4+6/Qgk9WBdlBVGD80KIf69qY8KHR2nVUnKVUkZwjatCnSiCQJpTCLcsGdUEZwcbOI4ayetirQNmumx/TCaCfIFDrt3MqdVa29bWq7lGppliIuidAyuRsAvs7r1tjAxc0mOP136hTpwdNXB1Wn+lKtgEI3Nq74+wdkv5tLM1Dk8CUYo5QzNKKz9jZpzOfV9ky5TdBAP4LewA0DtnBxIwCd1ZZm6UPHLfDe5bYoLotYMqXGxsaU2oMDsseNG6HQWY0nVcvlI2gGtLSIaluLNOH3CzhWxC3HzVz06pEaP4I6ABc3CqCzuniR71vLlvg+6cYoLgcxVYXJSFT17T+QqkOxi7ukbq5QPg6FDI+ZHdM8E6GgkBAEqMGyOscv0jpj+uitdfwI6hxc3Cjy/JMdU70e4WfTpkoXluHlx/BNGI2qNcmU6tl/QA6kZNXxvZ94rKwJidDcJGKJy4TXC7LPK+Baq3L40MgFz6uVCC5uDHjxzx0ntLZID/j9QlcF/Vj9kB666U8mQRvEJMuqF0XQyp3U14tKQ71WT6ahR2B4nAwBlKQThBX366LGSztKBBc3hvzzxRlXNdSLawUBplfsD8nJhouaS+Di5gBvvTTj9vo68QuYN6/4H7Z64aLmMri4OcTO7llYBHyD/sVFrjJAo+BRLmruhIubw3CRqwiwpOM+7n66Gy5uJYKLXFnSrQsar1MrA7i4lZgMkcMJJLOr+slwJ8bRcx3vKCgvuLi5iJ3ds67URe6Man8uXEC3Xnj7KD96lidc3FzIzu5Zy/Vo7mJ+ZHWUXj1Ku49HaeUPFzcXox9ZL+bRHFOMYydGaI9W8M9ZdXBxKxN2ds+akyF0ldT5UAowQlvPBa2y4eJWhnChs0V3RoTGj5xVABe3MkcXujW62K3hObrDGNHZem4KVCdc3CqMnd2z1ugit6bK8nSZYraedwxwuLhVOLrYLdfFbnmF1NKhkG3Qv1DMNvDIjJMNF7cqQ3dgl+tfczJ+78bjLIpYjy5ixq9cyDim4OLGOYwe5YEe5YEuesZyYtpHXEO4QBetUf1L+z1P+nNI4eLGsUWGEJqlh+fBOI4BAP8PK+smEQrdKqcAAAAASUVORK5CYII='
# #############################################
# GRANA! gerenciador de finanças pessoais
#
# - criar lista de anos com uma função
# - Comparar se ja existe registro igual no banco
# #############################################

meses = [(_('Janeiro')), (_('Fevereiro')), (_('Março')), (_('Abril')), (_('Maio')), (_('Junho')),
         (_('Julho')), (_('Agosto')), (_('Setembro')),
         (_('Outubro')), (_('Novembro')), (_('Dezembro'))]
dias = [(_('Dom')), (_('Seg')), (_('Ter')), (_('Qua')), (_('Qui')), (_('Sex')), (_('Sab'))]
ano_inicio = sg.user_settings_get_entry('-anoinicial-', datetime.today().year)
ano_agora = datetime.today().year
anos = list(range(ano_inicio, ano_agora + 6, +1))

arqdb = './db/grana.db'



logging.basicConfig(filename='errorlog.txt', level=logging.ERROR,
                    filemode='a',
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
                    datefmt='%d/%m/%Y %H:%M:%S')
logger = logging.getLogger(__name__)
logging.getLogger().addHandler(logging.StreamHandler())

locale.setlocale(locale.LC_ALL, '')
sg.user_settings_filename('grana.json','./')

regexData = re.compile(r'\d{2}/\d{2}/\d{4}')
regexDinheiro = re.compile(r'^(\d{1,}\,\d{2}?)$')
regexDia = re.compile(r'\b[0-3]{0,1}[0-9]{1}\b')

def mesatual():
    res = ''
    mesat = datetime.now()
    m = mesat.strftime('%m')
    if m == '01':
        res = meses[0]
    elif m == '02':
        res = meses[1]
    elif m == '03':
        res = meses[2]
    elif m == '04':
        res = meses[3]
    elif m == '05':
        res = meses[4]
    elif m == '06':
        res = meses[5]
    elif m == '07':
        res = meses[6]
    elif m == '08':
        res = meses[7]
    elif m == '09':
        res = meses[8]
    elif m == '10':
        res = meses[9]
    elif m == '11':
        res = meses[10]
    elif m == '12':
        res = meses[11]
    return res

def cria_db():
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    try:
        c.execute(
            'CREATE TABLE "movimento" ("mo_index" INTEGER, "mo_data" TEXT, '
            '"mo_tipo" TEXT, "mo_categoria" TEXT, '
            '"mo_descricao" TEXT, "mo_valor" REAL, "mo_relrec" INTEGER, PRIMARY KEY("mo_index"))'
        )
        conexao.commit()
        c.execute(
            'CREATE TABLE "categoria" ("ca_index" INTEGER, "ca_categoria" TEXT, PRIMARY KEY("ca_index"))'
        )
        conexao.commit()
        c.execute(
            'CREATE TABLE "recorrente" ("re_index" INTEGER, "re_dia" TEXT, '
            '"re_tipo" TEXT, "re_categoria" TEXT, "re_descricao" TEXT, '
            '"re_valor" REAL, "re_data_inicio" TEXT, PRIMARY KEY("re_index"))'
        )
        conexao.commit()
    except Exception as err:
        logger.error(err)
        print('Não foi possível criar o banco de dados: ', err)
    conexao.close()

def movimento_calcula_total(mesano):
    # retorna o valor total do movimento do mês
    mesano = '%' + mesano + '%'
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    c.execute('SELECT mo_tipo, mo_valor FROM movimento WHERE mo_data LIKE ?', (mesano,))
    resultado = c.fetchall()
    valor = 0.0
    for idx, x in enumerate(resultado):
        if x[0] == 'Entrada':
            valor = valor + x[1]
        else:
            valor = valor - x[1]
    return valor

def movimento_ler_indice(indice):
    # retorna data, tipo, categoria, descrição, valor, recorrente
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    c.execute('SELECT mo_data, mo_tipo, mo_categoria, '
              'mo_descricao, mo_valor, mo_relrec FROM movimento WHERE mo_index = ?', (indice,))
    resultado = c.fetchone()
    temp = str(resultado[4])
    temp = temp.replace('.', ',') + '0'
    resultado_final = [resultado[0], resultado[1], resultado[2], resultado[3], temp, resultado[5]]
    return resultado_final


def movimento_ler(mesano):
    # retorna indice, data, tipo, categoria, descrição, valor, R para recorrente e índice do recorrente
    mesano = '%' + mesano + '%'
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    c.execute('SELECT * FROM movimento WHERE mo_data LIKE ?', (mesano,))
    resultado = c.fetchall()
    resultado_final = []
    for idx, x in enumerate(resultado):
        if x[6] != 0:
            tmp_rec = 'R'
        else:
            tmp_rec = ''
        temp = [x[0], x[1], x[2], x[3], x[4], locale.currency(x[5]), tmp_rec, x[6]]
        resultado_final.append(temp)
    return resultado_final

def movimento_ler_recorrente(indice):
    # retorna dia e data de início
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    c.execute('SELECT re_dia, re_data_inicio FROM recorrente WHERE re_index = ?', (indice,))
    resultado = c.fetchone()
    return resultado


def movimento_grava(data, tipo, categoria, descricao, valor, relrec):
    dados = [data, tipo, categoria, descricao, valor, relrec]
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'INSERT INTO movimento(mo_data, mo_tipo, mo_categoria, ' \
              'mo_descricao, mo_valor, mo_relrec) VALUES (?, ?, ?, ?, ?, ?)'
    c.execute(comando, dados)
    conexao.commit()
    conexao.close()

def movimento_grava_recorrente(dia, tipo, categoria, descricao, valor, datainicio):
    dados = [dia, tipo, categoria, descricao, valor, datainicio]
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'INSERT INTO recorrente(re_dia, re_tipo, re_categoria, ' \
              're_descricao, re_valor, re_data_inicio) VALUES (?, ?, ?, ?, ?, ?)'
    c.execute(comando, dados)
    conexao.commit()
    indice_recorrente = c.lastrowid
    data_insercao = str(dia) + datainicio[2:]
    dif_meses = datetime.now().month - datetime.strptime(data_insercao, '%d/%m/%Y').month
    data_tmp = datetime.now() + relativedelta(day=int(dia))
    x = 0
    while x < dif_meses + 1:
        data_final = data_tmp - relativedelta(months=x)
        print(datetime.strftime(data_final, '%d/%m/%Y'))
        data_final_str = datetime.strftime(data_final, '%d/%m/%Y')
        movimento_grava(data_final_str, tipo, categoria, descricao, valor, indice_recorrente)
        x = x + 1
    conexao.close()

def movimento_integra():
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'SELECT re_index'

def movimento_atualiza(indice, data, tipo, categoria, descricao, valor):
    dados = [data, tipo, categoria, descricao, valor, indice]
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'UPDATE movimento SET mo_data = ?, mo_tipo = ?, ' \
              'mo_categoria = ?, mo_descricao = ?, mo_valor = ? WHERE mo_index = ?'
    c.execute(comando, dados)
    conexao.commit()
    conexao.close()


def movimento_atualiza_recorrente(indice, dia, tipo, categoria, descricao, valor, data_inicio):
    dados = [dia, tipo, categoria, descricao, valor, data_inicio, indice]
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'UPDATE recorrente SET re_dia = ?, re_tipo = ?, ' \
              're_categoria = ?, re_descricao = ?, re_valor = ?, re_data_inicio WHERE mo_index = ?'
    c.execute(comando, dados)
    conexao.commit()
    conexao.close()

def movimento_apaga(index):
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'DELETE FROM movimento WHERE mo_index = ?'
    c.execute(comando, (index,))
    conexao.commit()
    conexao.close()

def movimento_apaga_recorrente(index):
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'DELETE FROM recorrente WHERE re_index = ?'
    c.execute(comando, (index,))
    conexao.commit()
    dados = [0, index]
    comando = 'UPDATE movimento SET mo_relrec = ? WHERE mo_relrec = ?'
    c.execute(comando, dados)
    conexao.commit()
    conexao.close()

def movimento_apaga_recorrente_retro(index):
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = 'DELETE FROM recorrente WHERE re_index = ?'
    c.execute(comando, (index,))
    conexao.commit()
    dados = [index,]
    comando = 'DELETE FROM movimento WHERE mo_relrec = ?'
    c.execute(comando, dados)
    conexao.commit()
    conexao.close()

def mov_anual_categoria(categoria, ano):
    # retorna data da operação, descrição , valor
    tipo = 'Saída'
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = ('SELECT mo_data, mo_descricao, mo_valor FROM movimento '
               'WHERE mo_data LIKE ? AND mo_categoria LIKE ? AND mo_tipo = ?')
    categoria = '%' + categoria + '%'
    ano2 = '%' + str(ano) + '%'
    c.execute(comando, (ano2, categoria, tipo))
    resultado = c.fetchall()
    return resultado

def mov_anual_recebido(ano):
    # retorna data da operação, descrição , valor
    tipo = 'Entrada'
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    comando = ('SELECT mo_data, mo_descricao, mo_valor FROM movimento '
               'WHERE mo_data LIKE ? AND mo_tipo = ?')
    ano2 = '%' + str(ano) + '%'
    c.execute(comando, (ano2, tipo))
    resultado = c.fetchall()
    return resultado

def categorias_ler():
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    c.execute('SELECT ca_categoria FROM categoria')
    resultado = c.fetchall()
    resultado_list = []
    for idx, x in enumerate(resultado):
        resultado_list.append(''.join(x))
    print(resultado)
    print(resultado_list)
    conexao.close()
    return resultado_list

def categorias_apaga(categoria):
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    dados = ['Sem categoria', categoria]
    comando = 'UPDATE movimento SET mo_categoria = ? WHERE mo_categoria = ?'
    c.execute(comando, dados)
    conexao.commit()
    comando = 'DELETE FROM categoria WHERE ca_categoria = ?'
    c.execute(comando, (categoria,))
    conexao.commit()
    conexao.close()

def categorias_criar(categoria):
    conexao = sqlite3.connect(arqdb)
    c = conexao.cursor()
    c.execute('INSERT INTO categoria(ca_categoria) VALUES (?)', (categoria,))
    conexao.commit()
    conexao.close()

class splashscreen():
    tmp = sg.user_settings_get_entry('-splashscreen-', True)
    if tmp == True:
        sg.Window('Nada', [[sg.Image(data=logo_grande64)]], transparent_color=sg.theme_background_color(),
                  no_titlebar=True, keep_on_top=True).read(timeout=2000, close=True)


class funcao_principal:
    global _
    titulos = [(_('Indice')), (_('Data')), (_('Tipo')), (_('Categoria')),
               (_('Descrição')), (_('Valor')), (_('R')), (_('Indice recorrente'))]
    largura = [0, 10, 10, 30, 35, 10, 2, 0]
    visibilidade = [False, True, True, True, True, True, True, False]
    row = []
    dados = []
    tam_texto = 7
    tam_imput = 1
    atualiza = True
    indice_tmp = None
    indice_recorrente = 0
    linha_tmp = []
    def janela_recorrente(self):
        layout = [
            [sg.Text((_('Você está prestes a apagar um lançamento recorrente.')))],
            [sg.Text('Este lançamento começou a partir de {}.'.format(self.linha_tmp[1]))],
            [sg.Text((_('Você deseja apagá-lo daqui por diante ou retroativamente?')))],
            [sg.Push(), sg.B((_('Daqui por diante')), k='-DAQUI-'), sg.B((_('Retroativamente')), k='-RETRO-'),
             sg.B((_('Cancelar')), k='-CANCELA-')]
        ]
        return sg.Window((_('Apagar')), layout,
                         finalize=True)

    def janela_sobre(self):
        layout = [
            [sg.Text((_('Sobre')), font='_ 25')],
            [sg.HorizontalSeparator(k='-SEP-')],
            [sg.Text((_('A fazer...')))],
            [sg.Text((_('Quer personalizar sua cópia do programa? Digite seu nome abaixo:')))],
            [sg.I(s=(20, 1), k='-NOME-', default_text=sg.user_settings_get_entry('-usuario-', '')),
             sg.B((_('Gravar')), k='-GRAVA-')],
            [sg.Checkbox('Splashscreen', k='-SPLASH-', default=sg.user_settings_get_entry('-splashscreen-', True),
                         enable_events=True)],
            [sg.Push(), sg.B((_('Voltar')), k='-SAIR-')]
        ]
        return sg.Window((_('Sobre...')), layout,
                         finalize=True)

    def janela_cat(self):
        layout = [
            [sg.Text((_('Categorias')), font='_ 25')],
            [sg.HorizontalSeparator(k='-SEP-')],
            [sg.T((_('Categorias existentes: '))), sg.Combo(categorias_ler(), k='-CATEGORIAS-', s=30, readonly=True),
             sg.B((_('Apagar')), k='-APAGA-')],
            [sg.T((_('Cria nova categoria')))],
            [sg.Text((_('Nome da categoria:'))), sg.I(size=30, k='-NOMECAT-')],
            [sg.Push(), sg.B((_('Adicionar')), k='-ADICIONAR-'), sg.B((_('Voltar')), k='-VOLTAR-')]
        ]
        return sg.Window((_('Categorias')), layout,
                         finalize=True)


    def janela_gasto_anual_cat(self):
        tbl_titulos = [(_('Data')), (_('Descrição')), (_('Valor'))]
        tbl_largura = [10, 30, 10]
        layout = [
            [sg.Text((_('Gasto anual por categoria')), font='_ 25')],
            [sg.HorizontalSeparator(k='-SEP-')],
            [sg.T((_('Categoria: '))), sg.Combo(categorias_ler(), k='-CATEGORIAS-', s=30, readonly=True),
             sg.T((_('Ano:'))),
                        sg.Combo(anos, key='-ANO-', default_value=datetime.now().year,
                                 enable_events=True, readonly=True)],
            [sg.Table(values=[], headings=tbl_titulos,
                         # values=le_movimento(datetime.strftime(datetime.now(), '%m/%Y'))
                         col_widths=tbl_largura,
                         # visible_column_map=self.visibilidade,
                         auto_size_columns=False,  # justification='Left',
                         k='-TABELA-',
                         enable_events=True,
                         expand_x=True,
                         expand_y=True,
                         num_rows=16)],
            [sg.Push(), sg.T((_('Total:'))), sg.I(k='-TOTAL-', s=(14, 1))],
            [sg.Push(), sg.B((_('Preencher tabela')), k='-RESULTADO-'),sg.B((_('Voltar')), k='-VOLTAR-')]
        ]
        return sg.Window((_('Gasto anual por categoria')), layout,
                         finalize=True)

    def janela_recebido_anual(self):
        tbl_titulos = [(_('Data')), (_('Descrição')), (_('Valor'))]
        tbl_largura = [10, 30, 10]
        layout = [
            [sg.Text((_('Valor recebido por ano')), font='_ 25')],
            [sg.HorizontalSeparator(k='-SEP-')],
            [sg.T('Ano:'),
                        sg.Combo(anos, key='-ANO-', default_value=datetime.now().year,
                                 enable_events=True, readonly=True)],
            [sg.Table(values=[], headings=tbl_titulos,
                         # values=le_movimento(datetime.strftime(datetime.now(), '%m/%Y'))
                         col_widths=tbl_largura,
                         # visible_column_map=self.visibilidade,
                         auto_size_columns=False,  # justification='Left',
                         k='-TABELA-',
                         enable_events=True,
                         expand_x=True,
                         expand_y=True,
                         num_rows=16)],
            [sg.Push(), sg.T((_('Total:'))), sg.I(k='-TOTAL-', s=(14, 1))],
            [sg.Push(), sg.B((_('Preencher tabela')), k='-RESULTADO-'),sg.B((_('Voltar')), k='-VOLTAR-')]
        ]
        return sg.Window((_('Valor recebido anual')), layout,
                         finalize=True)


    def cria_janela(self):
        global _
        sg.theme(sg.user_settings_get_entry('-tema-', None))
        coluna1_def = sg.Column(
            [[sg.T(_('Data:')), sg.I(default_text=datetime.strftime(datetime.now(), '%d/%m/%Y'), k='-DATAMOV-',
                                  size=10),
              sg.CalendarButton((_('Data')), locale='pt_BR', format='%d/%m/%Y',
                                month_names=meses, day_abbreviations=dias, no_titlebar=False, title='Data'),
              sg.T((_('Tipo:'))),
              # sg.Combo(['Entrada', 'Saída'], default_value='Entrada'),
              sg.Radio((_('Entrada')), group_id='-ENSAI-', k='-ENTRADA-', default=True),
              sg.Radio((_('Saída')), group_id='-ENSAI-', k='-SAIDA-'),
              sg.T((_('Categoria:'))), sg.Combo(categorias_ler(), size=25, k='-CATEGORIA-', readonly=True)],
             [sg.T((_('Descrição:'))), sg.I(size=50, k='-DESCRICAO-'), sg.Push(), sg.T((_('Valor: R$'))),
              sg.I(size=15, k='-VALORMOV-')]
             # disabled=True,
             ])
        coluna3_def = sg.Column([
            [sg.B((_('Adicionar')), k='-ADICIONAR-', bind_return_key=True)],
            [sg.B((_('Atualizar')), k='-ATUALIZAR-', disabled=True)],
            [sg.B((_('Categorias')), k='-CATEGORIAS-')],
            [sg.B((_('Cancelar')), k='-CANCELAR-', disabled=True)]
        ])
        coluna2_def = sg.Column([
            [sg.Checkbox((_('É recorrente?')), k='-RECORRENTE-')],
            [sg.T((_('Dia do mês:'))), sg.I(size=3, k='-DIARECORRENTE-')],
            [sg.T((_('A partir de:'))),
             sg.I(default_text=datetime.strftime(datetime.now(), '%d/%m/%Y'), k='-DATARECORRENTE-', size=10)]
        ])

        # bloco_def = [[coluna1_def], [coluna2_def]
        #             ]

        menu_def = [['&Arquivo', ['Adicionar aluno', 'Imprimir relatório', 'Informações do aluno', '---', '&Sair']],
                    # 'Save::savekey',
                    ['&Editar', ['!Configurações', 'Mudar tema'], ],
                    ['&Relatórios', ['Categorias anual', 'Recebido anual']],
                    ['Gráficos',['Mensal por categorias', 'Anual por categorias']],
                    ['&Ferramentas', ['Backup parcial', 'Backup completo', 'Administração', ['Limpar banco de dados']]],
                    ['A&juda', ['Tela principal', 'Sobre...']], ]

        self.layout = [[sg.Menu(menu_def)],
                       [sg.Image(data=logo64),
                        sg.Text((_('Grana! finanças pessoais')), font='_ 25', key='-TITULO-')],
                       [sg.HorizontalSeparator(k='-SEP-')],
                       [sg.T((_('Mês:'))), sg.Combo(meses, key='-MES-',
                                               default_value=mesatual(), enable_events=True, readonly=True),
                        sg.T((_('Ano:'))),
                        sg.Combo(anos, key='-ANO-', default_value=datetime.now().year,
                                 enable_events=True, readonly=True)],
                       [
                        sg.Table(values=[], headings=self.titulos,
                                 # values=le_movimento(datetime.strftime(datetime.now(), '%m/%Y'))
                                 col_widths=self.largura,
                                 visible_column_map=self.visibilidade,
                                 auto_size_columns=False,  # justification='Left',
                                 k='-TABELA-',
                                 enable_events=True,
                                 expand_x=True,
                                 expand_y=True,
                                 num_rows=16)],
                       [sg.B((_('Alterar registro')), k='-ALTERA-'), sg.B((_('Apagar registro')), k='-APAGA-'),
                        sg.B((_('Gerar relatório em PDF')), k='-RELPDF-'),
                        sg.Push(), sg.T((_('Saldo:'))),
                        sg.I(
                             size=10, k='-SALDO-')],
                       [sg.Frame((_('Movimento')), [[coluna1_def, coluna2_def, coluna3_def]],
                                 k='-FRAME-')],  # , background_color='#a4a3a1'
                       # s=(800, 100),
                       [sg.Push(), sg.Button((_('Sair')), k='-SAIR-')]]

        return sg.Window('Grana!', self.layout, enable_close_attempted_event=True,
                         location=sg.user_settings_get_entry('-posicao-', (None, None)),
                         finalize=True)

    def __init__(self):
        self.window = self.cria_janela()

    def run(self):
        global _
        if self.atualiza:
            self.window.write_event_value('-ATUALIZA-', '')
            tmp = sg.user_settings_get_entry('-usuario-', '')
            if tmp != '':
                self.window['-TITULO-'].update(value='Grana! finanças pessoais de ' + tmp)
            else:
                self.window['-TITULO-'].update(value=(_('Grana! finanças pessoais')))
            atualiza = False

        while True:
            self.event, self.values = self.window.read()

            if self.event == '-TABELA-':
                self.row = self.values[self.event]
                self.dados = self.window['-TABELA-'].Values

            if self.event == '-ATUALIZA-':
                mes_int = datetime.strptime(self.values['-MES-'], '%B').month
                if mes_int < 10:
                    mes = '0' + str(mes_int)
                else:
                    mes = str(mes_int)
                mesano = mes + '/' + str(self.values['-ANO-'])
                self.window['-TABELA-'].update(values=movimento_ler(mesano))
                valor_total = locale.currency(movimento_calcula_total(mesano))
                self.window['-SALDO-'].update(value=valor_total)
                self.window['-CATEGORIA-'].update(values=categorias_ler())

            if self.event in ('-MES-', '-ANO-'):
                self.window.write_event_value('-ATUALIZA-', '')

            if self.event == (_('Recebido anual')):

                self.win = self.janela_recebido_anual()
                while True:
                    self.ev, self.val = self.win.read()
                    if self.ev == '-RESULTADO-':
                        tabela = []
                        valortotal = 0.0
                        if self.val['-ANO-'] != '':
                            tabela_tmp = mov_anual_recebido(self.val['-ANO-'])
                            for idx, x in enumerate(tabela_tmp):
                                tabela.append([x[0], x[1], locale.currency(x[2])])
                                valortotal = valortotal + x[2]
                            self.win['-TABELA-'].update(values=tabela)
                            self.win['-TOTAL-'].update(value=locale.currency(valortotal))
                        else:
                            sg.popup('Selecione um ano.')
                    if self.ev in (sg.WINDOW_CLOSED, '-VOLTAR-'):
                        break
                self.win.close()

            if self.event == (_('Categorias anual')):
                self.win = self.janela_gasto_anual_cat()
                while True:
                    self.ev, self.val = self.win.read()
                    if self.ev == '-RESULTADO-':
                        tabela = []
                        valortotal = 0.0
                        if self.val['-CATEGORIAS-'] != '':
                            print('categoria: ', self.val['-CATEGORIAS-'])
                            tabela_tmp = mov_anual_categoria(self.val['-CATEGORIAS-'], self.val['-ANO-'])
                            for idx, x in enumerate(tabela_tmp):
                                tabela.append([x[0], x[1], locale.currency(x[2])])
                                valortotal = valortotal + x[2]
                            self.win['-TABELA-'].update(values=tabela)
                            self.win['-TOTAL-'].update(value=locale.currency(valortotal))
                        else:
                            sg.popup((_('Selecione uma categoria.')))
                    if self.ev in (sg.WINDOW_CLOSED, '-VOLTAR-'):
                        break
                self.win.close()
                
            if self.event == (_('Mensal por categorias')):
                mes_int = datetime.strptime(self.values['-MES-'], '%B').month
                if mes_int < 10:
                    mes = '0' + str(mes_int)
                else:
                    mes = str(mes_int)
                mesano = mes + '/' + str(self.values['-ANO-'])
                gr.grafico_cat_mensal(mesano)

            if self.event == (_('Anual por categorias')):
                gr.grafico_cat_anual(str(self.values['-ANO-']))

            if self.event == (_('Mudar tema')):
                self.ev, self.vals = sg.Window((_('Escolha o tema')), [
                    [sg.Text(text=('Tema atual: {}'.format(sg.user_settings_get_entry('-tema-'))))],
                    [sg.Combo(sg.theme_list(), readonly=True, k='-THEME LIST-'),
                     sg.OK(button_text=(_('Aceitar'))), sg.Cancel(button_text=(_('Cancelar')))]]).read(
                    close=True)
                if self.ev == (_('Aceitar')):
                    self.window.close()
                    sg.user_settings_set_entry('-tema-', self.vals['-THEME LIST-'])
                    self.window = self.cria_janela()
                    self.window.write_event_value('-ATUALIZA-', '')

            if self.event == '-ADICIONAR-':
                ensai = ''
                if self.values['-ENTRADA-']:
                    ensai = 'Entrada'
                else:
                    ensai = 'Saída'
                 # começa checando os valores por erros
                if self.values['-DATAMOV-'] == '' or not re.fullmatch(regexData, self.values['-DATAMOV-']):
                    sg.popup((_('Campo data inválido.')))
                elif self.values['-CATEGORIA-'] == '':
                    sg.popup((_('Você deve escolher uma categoria.')))
                elif self.values['-DESCRICAO-'] == '':
                    sg.popup((_('Campo descrição não pode estar vazio.')))
                elif self.values['-VALORMOV-'] == '' or not re.fullmatch(regexDinheiro, self.values['-VALORMOV-']):
                    sg.popup((_('Campo valor inválido.')))
                elif self.values['-RECORRENTE-'] and self.values['-DIARECORRENTE-'] == '':
                    sg.popup((_('Se o movimento é recorrente, preencha o campo Dia do mês.')))
                elif self.values['-RECORRENTE-'] and not re.fullmatch(regexData, self.values['-DATARECORRENTE-']):
                    sg.popup((_('A data de início do movimento recorrente está errada.')))
                else:
                    self.ev, self.vals = sg.Window((_('Confirma')), [
                        [sg.Text((_('Deseja gravar este movimento:')))],
                        [sg.Text((_('Data:')), size=self.tam_texto), sg.I(default_text=self.values['-DATAMOV-'], size=10),
                         sg.Push(), sg.Text((_('Tipo:')), size=self.tam_texto), sg.I(default_text=ensai, size=10)],
                        [sg.Text((_('Categoria:')), size=self.tam_texto), sg.I(default_text=self.values['-CATEGORIA-'])],
                        [sg.Text((_('Descrição:')), size=self.tam_texto), sg.I(default_text=self.values['-DESCRICAO-'])],
                        [sg.Text((_('Valor:')), size=self.tam_texto), sg.I(default_text=self.values['-VALORMOV-'], size=12)],
                        [sg.Push(), sg.OK(button_text=(_('Sim'))), sg.Cancel(button_text=(_('Não')))]]).read(
                        close=True)
                    if self.ev == (_('Não')):
                        sg.popup('Operação cancelada.')
                    else:
                        valor = float(self.values['-VALORMOV-'].replace(',', '.'))
                        if not self.values['-RECORRENTE-']:
                            try:
                                movimento_grava(
                                    self.values['-DATAMOV-'],
                                    ensai,
                                    self.values['-CATEGORIA-'],
                                    self.values['-DESCRICAO-'],
                                    valor,
                                    0
                                )
                                sg.popup((_('Movimento gravado com sucesso.')))
                            except Exception as err:
                                logger.error(err)
                                sg.popup((_('Ocorreu um erro durante a gravação dos dados.')))
                            finally:
                                pass
                        else:
                            try:
                                tmp_data = self.values['-DIARECORRENTE-'] + self.values['-DATARECORRENTE-'][2:]
                                movimento_grava_recorrente(
                                    self.values['-DIARECORRENTE-'],
                                    ensai,
                                    self.values['-CATEGORIA-'],
                                    self.values['-DESCRICAO-'],
                                    valor,
                                    tmp_data
                                )
                                sg.popup((_('Movimento recorrente gravado com sucesso!')))
                            except Exception as err:
                                sg.popup((_('Erro na gravação do movimento.')))
                                logger.error(err)
                            finally:
                                pass
                            self.window['-DIARECORRENTE-'].update(value='')
                            self.window['-RECORRENTE-'].update(value=False)
                        self.window.write_event_value('-ATUALIZA-', '')
                        self.window['-DATAMOV-'].update(value=datetime.strftime(datetime.now(), '%d/%m/%Y'))
                        self.window['-ENTRADA-'].update(value=True)
                        self.window['-CATEGORIA-'].update(value='')
                        self.window['-DESCRICAO-'].update(value='')
                        self.window['-VALORMOV-'].update(value='')

            if self.event == '-ALTERA-':
                if len(self.row) != 0:
                    self.window['-CANCELAR-'].update(disabled=False)
                    self.indice_tmp = self.dados[self.row[0]][0]
                    dados_tmp = movimento_ler_indice(self.indice_tmp)
                    print(dados_tmp)
                    self.window['-DATAMOV-'].update(value=dados_tmp[0])
                    if dados_tmp[1] == 'Entrada':
                        self.window['-ENTRADA-'].update(value=True)
                    else:
                        self.window['-SAIDA-'].update(value=True)
                    self.window['-CATEGORIA-'].update(value=dados_tmp[2])
                    self.window['-DESCRICAO-'].update(value=dados_tmp[3])
                    self.window['-VALORMOV-'].update(value=dados_tmp[4])
                    if dados_tmp[5] != 0:
                        self.indice_recorrente = dados_tmp[5]
                        self.window['-RECORRENTE-'].update(value=True)
                        dados_recorrente = movimento_ler_recorrente(dados_tmp[5])
                        print(dados_tmp[5])
                        print(dados_recorrente)
                        self.window['-DIARECORRENTE-'].update(value=dados_recorrente[0])
                        self.window['-DATARECORRENTE-'].update(value=dados_recorrente[1])
                    self.window['-ATUALIZAR-'].update(disabled=False)
                    self.window['-ADICIONAR-'].update(disabled=True)
                else:
                    sg.popup((_('Selecione um registro da tabela.')))

            if self.event == '-CANCELAR-':
                self.window['-ENTRADA-'].update(value=True)
                self.window['-CATEGORIA-'].update(value='')
                self.window['-DESCRICAO-'].update(value='')
                self.window['-VALORMOV-'].update(value='')
                self.window['-RECORRENTE-'].update(value=False)
                self.window['-DIARECORRENTE-'].update(value='')
                self.window['-DATARECORRENTE-'].update(value=datetime.strftime(datetime.now(), '%d/%m/%Y'))
                self.window['-ATUALIZAR-'].update(disabled=True)
                self.window['-ADICIONAR-'].update(disabled=False)
                self.window['-CANCELAR-'].update(disabled=True)
                self.window['-DATAMOV-'].update(value=datetime.strftime(datetime.now(), '%d/%m/%Y'))

            if self.event == '-ATUALIZAR-':
                ensai = ''
                if self.values['-ENTRADA-']:
                    ensai = 'Entrada'
                else:
                    ensai = 'Saída'
                 # começa checando os valores por erros
                if self.values['-DATAMOV-'] == '' or not re.fullmatch(regexData, self.values['-DATAMOV-']):
                    sg.popup((_('Campo data inválido.')))
                elif self.values['-CATEGORIA-'] == '':
                    sg.popup((_('Você deve escolher uma categoria.')))
                elif self.values['-DESCRICAO-'] == '':
                    sg.popup((_('Campo descrição não pode estar vazio.')))
                elif self.values['-VALORMOV-'] == '' or not re.fullmatch(regexDinheiro, self.values['-VALORMOV-']):
                    sg.popup((_('Campo valor inválido.')))
                elif self.indice_recorrente != 0 and self.values['-DIARECORRENTE-'] == '':
                    sg.popup((_('Dia de recorrência não pode ser vazio.')))
                elif self.indice_recorrente != 0 and not re.fullmatch(regexData, self.values['-DATARECORRENTE-']):
                    sg.popup((_('Data de início da recorrência inválida.')))
                elif self.indice_recorrente != 0 and not self.values['-RECORRENTE-']:
                    sg.popup((_('Atenção: este registro é recorrente. '
                                'Não é possível converter entre tipos de registro.')))
                elif self.indice_recorrente == 0 and self.values['-RECORRENTE-']:
                    sg.popup((_('Atenção: este registro não é recorrente. '
                             'Não é possível converter entre tipos de registro.')))
                else:
                    valor = float(self.values['-VALORMOV-'].replace(',', '.'))
                    if self.indice_recorrente != 0:
                        try:
                            movimento_atualiza_recorrente(
                                self.indice_recorrente,
                                self.values['-DIARECORRENTE-'],
                                ensai,
                                self.values['-CATEGORIA-'],
                                self.values['-DESCRICAO-'],
                                valor,
                                self.values['-DATARECORRENTE-']
                            )
                            sg.popup((_('Movimento atualizado com sucesso.')))
                            self.window['-DIARECORRENTE-'].update(value='')
                            self.window['-RECORRENTE-'].update(value=False)
                        except Exception as err:
                            logger.error(err)
                            sg.popup((_('Ocorreu um erro durante a gravação dos dados.')))
                        finally:
                            pass
                    else:
                        try:
                            movimento_atualiza(
                                self.indice_tmp,
                                self.values['-DATAMOV-'],
                                ensai,
                                self.values['-CATEGORIA-'],
                                self.values['-DESCRICAO-'],
                                valor
                            )
                            sg.popup((_('Movimento atualizado com sucesso.')))
                        except Exception as err:
                            logger.error(err)
                            sg.popup((_('Ocorreu um erro durante a gravação dos dados.')))
                        finally:
                            pass
                    self.window.write_event_value('-ATUALIZA-', '')
                    self.window['-ATUALIZAR-'].update(disabled=True)
                    self.window['-ADICIONAR-'].update(disabled=False)
                    self.window['-DATAMOV-'].update(value=datetime.strftime(datetime.now(), '%d/%m/%Y'))
                    self.window['-ENTRADA-'].update(value=True)
                    self.window['-CATEGORIA-'].update(value='')
                    self.window['-DESCRICAO-'].update(value='')
                    self.window['-VALORMOV-'].update(value='')

            if self.event == '-CATEGORIAS-':
                self.win = self.janela_cat()
                while True:
                    self.ev, self.val = self.win.read()

                    if self.ev == '-APAGA-':
                        categoria = self.val['-CATEGORIAS-']
                        opcao, _ = sg.Window((_('Continuar?')), [[sg.T((_('Tem certeza? Os registros não serão apagados.')))],
                                                            [sg.Yes(s=10, button_text=(_('Sim'))),
                                                             sg.No(s=10, button_text=(_('Não')))]],
                                             disable_close=True, modal=True).read(close=True)
                        if opcao == (_('Sim')):
                            categorias_apaga(categoria)
                            sg.popup((_('Categoria excluída com sucesso.')))
                            self.win['-CATEGORIAS-'].update(values=categorias_ler())

                    if self.ev == '-ADICIONAR-':
                        categoria = self.val['-NOMECAT-']
                        categorias_criar(categoria)
                        sg.popup((_('Nova categoria criada com sucesso.')))
                        self.win['-CATEGORIAS-'].update(values=categorias_ler())
                        self.win['-NOMECAT-'].update(value='')

                    if self.ev in (sg.WINDOW_CLOSED, '-VOLTAR-'):
                        self.window.write_event_value('-ATUALIZA-', '')
                        break
                self.win.close()

            if self.event == 'Sobre...':
                self.win = self.janela_sobre()
                while True:
                    self.ev, self.val = self.win.read()

                    if self.ev == '-GRAVA-':
                        if self.val['-NOME-'] != '' and \
                                self.val['-NOME-'] != sg.user_settings_get_entry('-usuario-', ''):
                            sg.user_settings_set_entry('-usuario-', self.val['-NOME-'])
                            sg.popup((_('Usuário gravado com sucesso!')))
                            self.window['-TITULO-'].update(value='Grana! finanças pessoais de ' + self.val['-NOME-'])
                        else:
                            sg.popup((_('Campo não pode ser vazio, e deve ser diferente do valor anterior.')))
                    if self.ev == '-SPLASH-':
                        if self.val['-SPLASH-']:
                            sg.user_settings_set_entry('-splashscreen-', True)
                        else:
                            sg.user_settings_set_entry('-splashscreen-', False)
                    if self.ev in (sg.WINDOW_CLOSED, '-SAIR-'):
                        break
                self.win.close()

            if self.event == '-APAGA-':
                if len(self.row) != 0:
                    if self.dados[self.row[0]][6] != '':
                        print('é recorrente!')
                        self.linha_tmp = movimento_ler_recorrente(self.dados[self.row[0]][7])
                        print(self.dados[self.row[0]][7])
                        print(self.linha_tmp)
                        self.win = self.janela_recorrente()
                        while True:
                            self.ev, self.val = self.win.read()
                            if self.ev == '-DAQUI-':
                                print('daqui por diante')
                                try:
                                    movimento_apaga_recorrente(self.dados[self.row[0]][7])
                                    sg.popup((_('Movimento excluído com sucesso.')))
                                    self.window.write_event_value('-ATUALIZA-', '')
                                except Exception as err:
                                    logger.error(err)
                                    sg.popup((_('Ocorreu um erro durante a exclusão do movimento.')))
                                finally:
                                    break
                            elif self.ev == '-RETRO-':
                                print('retroativamente')
                                try:
                                    movimento_apaga_recorrente_retro(self.dados[self.row[0]][7])
                                    sg.popup((_('Movimento excluído com sucesso.')))
                                    self.window.write_event_value('-ATUALIZA-', '')
                                except Exception as err:
                                    logger.error(err)
                                    sg.popup((_('Ocorreu um erro durante a exclusão do movimento.')))
                                finally:
                                    break
                            elif self.ev == '-CANCELA-':
                                sg.popup((_('Operação cancelada.')))
                                break
                        self.win.close()
                    else:
                        print('self dados self row 0 ', self.dados[self.row[0]])
                        print('self row ', self.row)
                        print('self dados', self.dados)
                        self.ev, self.vals = sg.Window((_('Confirma')), [
                            [sg.Text((_('Tem certeza que deseja apagar este lançamento?')))],
                            [sg.Text((_('Data:')), size=self.tam_texto),
                             sg.I(default_text=self.dados[self.row[0]][1], size=10),
                             sg.Push(), sg.Text((_('Tipo:')), size=self.tam_texto),
                             sg.I(default_text=self.dados[self.row[0]][2], size=10)],
                            [sg.Text((_('Categoria:')), size=self.tam_texto), sg.I(default_text=self.dados[self.row[0]][3])],
                            [sg.Text((_('Descrição:')), size=self.tam_texto), sg.I(default_text=self.dados[self.row[0]][4])],
                            [sg.Text((_('Valor:')), size=self.tam_texto),
                             sg.I(default_text=self.dados[self.row[0]][5], size=12)],
                            [sg.Push(), sg.OK(button_text=(_('Sim'))), sg.Cancel(button_text=(_('Não')))]]).read(
                            close=True)
                        if self.ev == (_('Sim')):
                            try:
                                movimento_apaga(self.dados[self.row[0]][0])
                                sg.popup((_('Movimento excluído com sucesso.')))
                                self.window.write_event_value('-ATUALIZA-', '')
                            except Exception as err:
                                logger.error(err)
                                sg.popup((_('Ocorreu um erro durante a exclusão do movimento.')))
                            finally:
                                pass

            if self.event in (sg.WINDOW_CLOSE_ATTEMPTED_EVENT, '-SAIR-', (_('Sair'))):
                sg.user_settings_set_entry('-posicao-', self.window.current_location())
                break
        self.window.close()

firstrun = sg.user_settings_get_entry('-firstrun-', True)
if firstrun:
    cria_db()
    sg.user_settings_set_entry('-anoinicial-', datetime.today().year)
    sg.user_settings_set_entry('-firstrun-', False)


splashscreen()
obj_principal = funcao_principal()
obj_principal.run()